(function(){if(!window.ymPrompt){window.ymPrompt={version:"4.0",pubDate:"2009-02-03",apply:function(b,f,j){j&&ymPrompt.apply(b,j);if(b&&f&&typeof f=="object")for(var g in f)b[g]=f[g];return b},eventList:[]};for(var S=["getPage","resizeWin","doHandler","close","setDefaultCfg","show"],E={},w;w=S.shift();)ymPrompt[w]=eval("0,function(){E."+w+"=arguments}");var F=/MSIE (\d)\./.test(navigator.userAgent)&&parseInt(RegExp.$1)<7,k=function(b){return document.getElementById(b)},q=new Function("env",
"fn","obj",["obj=obj||document;",window.attachEvent?"obj.attachEvent('on'+env,fn)":"obj.addEventListener(env,fn,false)",";ymPrompt.eventList.push([env,fn,obj])"].join("")),s=new Function("env","fn","obj",["obj=obj||document;",window.attachEvent?"obj.detachEvent('on'+env,fn)":"obj.removeEventListener(env,fn,false)"].join("")),i=function(b,f,j){if(b)if(typeof f=="object")for(var g in f)i(b,g,f[g]);else if(b instanceof Array||/htmlcollection|nodelist/i.test(""+b))for(g=b.length-1;g>=0;g--)i(b[g],f,j);
else b.style[f]=j},l=0,m,T=0,G=function(b,f,j,g){if(b){if(b instanceof Array){var o;for(f=[];b.length;)(o=b.shift())&&f[f.push(G.apply(null,{OK:[c.okTxt,"ok"],CANCEL:[c.cancelTxt,"cancel"]}[o]||o))-1]||f.pop();return f}g=g||"ymPrompt_btn_"+T++;j=typeof j=="undefined"?"undefined":!!j;return{id:g,html:"<input type='button' id='"+g+"' onclick='ymPrompt.doHandler(\""+f+'",'+j+")' style='cursor:pointer' class='btnStyle handler' value='"+b+"' />"}}},U=function(b){if(!b)return m="";b instanceof Array||(b=
[b]);if(!b.length)return m="";m=b.concat();for(var f=[];b.length;)f.push(b.shift().html);return f.join("&nbsp;&nbsp;")},x={titleBar:true,fixPosition:false,dragOut:false,autoClose:true,showMask:true,maskAlphaColor:"#000",maskAlpha:0.1,title:"\u6807\u9898",message:"\u5185\u5bb9",width:300,height:185,winPos:"c",iframe:false,btn:null,closeTxt:"\u5173\u95ed",okTxt:" \u786e \u5b9a ",cancelTxt:" \u53d6 \u6d88 ",icoCls:"",handler:function(){}},c={};(function(){if(!document.body||typeof document.body!="object")return q("load",
arguments.callee,window);var b=document.compatMode=="CSS1Compat"?document.documentElement:document.body,f=function(){ymPrompt.apply(g,{offX:h.offsetLeft-b.scrollLeft,offY:h.offsetTop-b.scrollTop})},j=document.createElement("div");j.innerHTML=["<div id='maskLevel' style='position:absolute;top:0;left:0;display:none;text-align:center;z-index:10000;'></div>",F?"<iframe id='maskIframe' style='position:absolute;top:0;left:0;display:none;text-align:center;z-index:9999;filter:alpha(opacity=0);opacity:0'></iframe>":
"","<div id='ym-window' style='position:absolute;z-index:10001;display:none'>",F?"<iframe style='width:100%;height:100%;position:absolute;top:0;left:0;z-index:-1'></iframe>":"","<div class='ym-tl' id='ym-tl'><div class='ym-tr'><div class='ym-tc' style='cursor:move;'><div class='ym-header-text'></div><div class='ym-header-tools'></div></div></div></div><div class='ym-ml' id='ym-ml'><div class='ym-mr'><div class='ym-mc'><div class='ym-body'></div></div></div></div><div class='ym-ml' id='ym-btnl'><div class='ym-mr'><div class='ym-btn'></div></div></div><div class='ym-bl' id='ym-bl'><div class='ym-br'><div class='ym-bc'></div></div></div></div>"].join("");
document.body.appendChild(j);j=null;var g={},o=k("maskLevel"),y=k("maskIframe"),h=k("ym-window"),z=k("ym-tl"),r=z.firstChild.firstChild,A=r.firstChild,H=A.nextSibling,t=k("ym-ml").firstChild.firstChild.firstChild,u=k("ym-btnl"),V=u.firstChild.firstChild,I=k("ym-bl"),J=function(a){a=a||window.event;var d=g.offX+(a.x||a.pageX);a=g.offY+(a.y||a.pageY);if(!c.dragOut){var e=b.scrollLeft,p=b.scrollTop;d=Math.min(Math.max(d,e),b.clientWidth-h.offsetWidth+e);a=Math.min(Math.max(a,p),b.clientHeight-h.offsetHeight+
p)}try{i(h,{left:d+"px",top:a+"px"})}catch(B){}},v=function(){var a=r.releaseCapture&&r;s("mousemove",J,a);s("mouseup",v,a);f();a&&(s("losecapture",v,a),a.releaseCapture())};q("mousedown",function(a){a=a||window.event;ymPrompt.apply(g,{offX:h.offsetLeft-(a.x||a.pageX),offY:h.offsetTop-(a.y||a.pageY)});a=r.setCapture&&r;q("mousemove",J,a);q("mouseup",v,a);a&&(q("losecapture",v,a),a.setCapture())},r);var W=function(a){a=a||event;a.keyCode==27&&C();if(m){var d=m.length,e;document.activeElement.id!=m[l].id&&
(e=true);if(a.keyCode==9||a.keyCode==39){e&&(l=-1);k(m[++l==d?--l:l].id).focus()}if(a.keyCode==37){e&&(l=d);k(m[--l<0?++l:l].id).focus()}if(a.keyCode==13)return true}if(a.keyCode>110&&a.keyCode<123||a.keyCode==9||a.keyCode==13)try{a.returnValue=!(a.cancelBubble=true);a.keyCode=0}catch(p){try{a.stopPropagation();a.preventDefault()}catch(B){}}},X=function(){i(h,{left:g.offX+b.scrollLeft+"px",top:g.offY+b.scrollTop+"px"})};o.oncontextmenu=h.onselectstart=h.oncontextmenu=function(){return false};var K=
function(){i([o,y],{width:b.scrollWidth+"px",height:b.scrollHeight+"px",display:""})},L=function(){i([o,y],"display","none");!+"\u000b1"?setTimeout(K,0):K()},M=function(a){if(c.showMask){i([o,y],"display","none");(a===false?s:q)("resize",L,window);if(a!==false){i(o,{background:c.maskAlphaColor,filter:"alpha(opacity="+c.maskAlpha*100+")",opacity:c.maskAlpha});L()}}},N=function(a){var d=[b.clientWidth-h.offsetWidth,b.clientHeight-h.offsetHeight,b.scrollLeft,b.scrollTop];a=a.replace(/\{(\d)\}/g,function(e,
p){return d[p]}).split(",");return[eval(a[0]),eval(a[1])]},O={c:"{0}/2+{2},{1}/2+{3}",l:"{2},{1}/2+{3}",r:"{0}+{2},{1}/2+{3}",t:"{0}/2+{2},{3}",b:"{0}/2,{1}+{3}",lt:"{2},{3}",lb:"{2},{1}+{3}",rb:"{0}+{2},{1}+{3}",rt:"{0}+{2},{3}"},P=function(a,d){if(!(!h||h.style.display=="none")){c.height=parseInt(d)||x.height;c.width=parseInt(a)||x.width;i(h,{left:0,top:0,width:c.width+"px",height:c.height+"px"});var e=O[c.winPos];e=e?N(e):c.winPos;e instanceof Array||(e=N(O.c));i(h,{top:e[1]+"px",left:e[0]+"px"});
f();i(t,"height",c.height-(parseInt(z.style.height)||z.offsetHeight)-(parseInt(u.style.height)||u.offsetHeight)-(parseInt(I.style.height)||I.offsetHeight)+"px")}},D=[],Q=function(a){var d=a===false?s:q;c.fixPosition&&d("scroll",X,window);d("keydown",W);if(a===false){i(h,"display","none");i(D,"visibility","visible");D=[]}else{a=document.getElementsByTagName("object");for(d=a.length-1;d>-1;d--)a[d].style.visibility!="hidden"&&D.push(a[d])&&(a[d].style.visibility="hidden");i([A,H],"display",c.titleBar?
"":"none");r.className="ym-tc"+(c.titleBar?"":" ym-ttc");A.innerHTML=c.title;H.innerHTML="<div class='ymPrompt_close' title='"+c.closeTxt+"' onclick='ymPrompt.doHandler(\"close\")'>&nbsp;</div>";if(c.iframe){var ifmStyle = 'position:absolute;width:100%;height:100%;top:0;left:0;opacity:1;filter:alpha(opacity=100)';a="";if(typeof c.iframe=="object")for(var e in c.iframe)a+=" "+e+'="'+c.iframe[e]+'"';t.innerHTML="<iframe style='" + ifmStyle+ "'" + a +' width="100%" height="100%" border="0" frameborder="0" src="'+c.message+'"></iframe>'}else t.innerHTML='<div class="ym-content">'+c.message+"</div>";t.className="ym-body "+c.icoCls;i(u,
"display",(V.innerHTML=U(G(c.btn)))?"":"none");i(h,"display","");P(c.width,c.height);m&&k(m[l=0].id).focus()}},C=function(){M(false);Q(false)};ymPrompt.apply(ymPrompt,{close:C,getPage:function(){return t.firstChild.tagName.toLowerCase()=="iframe"?t.firstChild:null},show:function(a,d){var e=Array.prototype.slice.call(a,0),p={};if(typeof e[0]!="object")for(var B=["message","width","height","title","handler","maskAlphaColor","maskAlpha","iframe","icoCls","btn","autoClose","fixPosition","dragOut","titleBar",
"showMask","winPos"],n=0,Y=e.length;n<Y;n++){if(e[n])p[B[n]]=e[n]}else p=e[0];ymPrompt.apply(c,ymPrompt.apply({},p,d),ymPrompt.setDefaultCfg());for(n in c)c[n]=c[n]!=null?c[n]:ymPrompt.cfg[n];M();Q()},doHandler:function(a,d){if(typeof d=="undefined"?c.autoClose:d)C();eval(c.handler)(a)},resizeWin:P,setDefaultCfg:function(a){return ymPrompt.cfg=ymPrompt.apply({},a,ymPrompt.apply({},ymPrompt.cfg,x))}});ymPrompt.setDefaultCfg();for(var R in E)ymPrompt[R].apply(null,E[R]);q("unload",function(){for(;ymPrompt.eventList.length;)s.apply(null,
ymPrompt.eventList.shift())},window)})()}})();ymPrompt.apply(ymPrompt,{alert:function(){ymPrompt.show(arguments,{icoCls:"ymPrompt_alert",btn:["OK"]})},succeedInfo:function(){ymPrompt.show(arguments,{icoCls:"ymPrompt_succeed",btn:["OK"]})},errorInfo:function(){ymPrompt.show(arguments,{icoCls:"ymPrompt_error",btn:["OK"]})},confirmInfo:function(){ymPrompt.show(arguments,{icoCls:"ymPrompt_confirm",btn:["OK","CANCEL"]})},win:function(){ymPrompt.show(arguments)}});
