var json=[
{"provname":"安徽","zone":"华东","city1":[
	{"city1name":"安庆市","city2":[
		{"city2name":"安庆市"},
		{"city2name":"枞阳县"},
		{"city2name":"大观区"},
		{"city2name":"怀宁县"},
		{"city2name":"潜山县"},
		{"city2name":"宿松县"},
		{"city2name":"太湖县"},
		{"city2name":"桐城市"},
		{"city2name":"望江县"},
		{"city2name":"迎江区"},
		{"city2name":"岳西县"}	]},
	{"city1name":"蚌埠市","city2":[
		{"city2name":"蚌埠市"},
		{"city2name":"东市区"},
		{"city2name":"固镇县"},
		{"city2name":"怀远县"},
		{"city2name":"郊区"},
		{"city2name":"五河县"},
		{"city2name":"西市区"},
		{"city2name":"中市区"}	]},
	{"city1name":"亳州市","city2":[
		{"city2name":"亳州市"},
		{"city2name":"利辛县"},
		{"city2name":"蒙城县"},
		{"city2name":"谯城区"},
		{"city2name":"涡阳县"}	]},
	{"city1name":"巢湖市","city2":[
		{"city2name":"巢湖市"},
		{"city2name":"含山县"},
		{"city2name":"和县"},
		{"city2name":"居巢区"},
		{"city2name":"庐江县"},
		{"city2name":"无为县"}	]},
	{"city1name":"池州市","city2":[
		{"city2name":"池州市"},
		{"city2name":"东至县"},
		{"city2name":"贵池区"},
		{"city2name":"青阳县"},
		{"city2name":"石台县"}	]},
	{"city1name":"滁州市","city2":[
		{"city2name":"滁州市"},
		{"city2name":"定远县"},
		{"city2name":"凤阳县"},
		{"city2name":"来安县"},
		{"city2name":"琅琊区"},
		{"city2name":"明光市"},
		{"city2name":"南谯区"},
		{"city2name":"全椒县"},
		{"city2name":"天长市"}	]},
	{"city1name":"阜阳市","city2":[
		{"city2name":"阜南县"},
		{"city2name":"阜阳市"},
		{"city2name":"界首市"},
		{"city2name":"临泉县"},
		{"city2name":"太和县"},
		{"city2name":"颍东区"},
		{"city2name":"颍泉区"},
		{"city2name":"颍上县"},
		{"city2name":"颍州区"}	]},
	{"city1name":"合肥市","city2":[
		{"city2name":"包河区"},
		{"city2name":"长丰县"},
		{"city2name":"肥东县"},
		{"city2name":"肥西县"},
		{"city2name":"合肥市"},
		{"city2name":"庐阳区"},
		{"city2name":"蜀山区"},
		{"city2name":"瑶海区"}	]},
	{"city1name":"淮北市","city2":[
		{"city2name":"杜集区"},
		{"city2name":"淮北市"},
		{"city2name":"烈山区"},
		{"city2name":"濉溪县"},
		{"city2name":"相山区"}	]},
	{"city1name":"淮南市","city2":[
		{"city2name":"八公山区"},
		{"city2name":"大通区"},
		{"city2name":"凤台县"},
		{"city2name":"淮南市"},
		{"city2name":"潘集区"},
		{"city2name":"田家庵区"},
		{"city2name":"谢家集区"}	]},
	{"city1name":"黄山市","city2":[
		{"city2name":"黄山区"},
		{"city2name":"黄山市"},
		{"city2name":"徽州区"},
		{"city2name":"祁门县"},
		{"city2name":"屯溪区"},
		{"city2name":"歙县"},
		{"city2name":"休宁县"},
		{"city2name":"黟县"}	]},
	{"city1name":"六安市","city2":[
		{"city2name":"霍邱县"},
		{"city2name":"霍山县"},
		{"city2name":"金安区"},
		{"city2name":"金寨县"},
		{"city2name":"六安市"},
		{"city2name":"寿县"},
		{"city2name":"舒城县"},
		{"city2name":"裕安区"}	]},
	{"city1name":"马鞍山市","city2":[
		{"city2name":"当涂县"},
		{"city2name":"花山区"},
		{"city2name":"金家庄区"},
		{"city2name":"马鞍山市"},
		{"city2name":"雨山区"}	]},
	{"city1name":"宿州市","city2":[
		{"city2name":"砀山县"},
		{"city2name":"灵璧县"},
		{"city2name":"泗县"},
		{"city2name":"宿州市"},
		{"city2name":"萧县"},
		{"city2name":"埇桥区"}	]},
	{"city1name":"铜陵市","city2":[
		{"city2name":"狮子山区"},
		{"city2name":"铜官山区"},
		{"city2name":"铜陵市"},
		{"city2name":"铜陵县"}	]},
	{"city1name":"芜湖市","city2":[
		{"city2name":"繁昌县"},
		{"city2name":"镜湖区"},
		{"city2name":"鸠江区"},
		{"city2name":"马塘区"},
		{"city2name":"南陵县"},
		{"city2name":"芜湖市"},
		{"city2name":"芜湖县"},
		{"city2name":"新芜区"}	]},
	{"city1name":"宣城市","city2":[
		{"city2name":"广德县"},
		{"city2name":"绩溪县"},
		{"city2name":"泾县"},
		{"city2name":"旌德县"},
		{"city2name":"郎溪县"},
		{"city2name":"宁国市"},
		{"city2name":"宣城市"},
		{"city2name":"宣州区"}	]} ]},
{"provname":"北京","zone":"华北","city1":[
	{"city1name":"北京","city2":[
		{"city2name":"北京"},
		{"city2name":"昌平区"},
		{"city2name":"朝阳区"},
		{"city2name":"崇文区"},
		{"city2name":"大兴区"},
		{"city2name":"东城区"},
		{"city2name":"房山区"},
		{"city2name":"丰台区"},
		{"city2name":"海淀区"},
		{"city2name":"怀柔区"},
		{"city2name":"门头沟区"},
		{"city2name":"密云县"},
		{"city2name":"平谷区"},
		{"city2name":"石景山区"},
		{"city2name":"顺义区"},
		{"city2name":"通州区"},
		{"city2name":"西城区"},
		{"city2name":"宣武区"},
		{"city2name":"延庆县"}	]} ]},
{"provname":"福建","zone":"华东","city1":[
	{"city1name":"福州市","city2":[
		{"city2name":"仓山区"},
		{"city2name":"长乐市"},
		{"city2name":"福清市"},
		{"city2name":"福州市"},
		{"city2name":"鼓楼区"},
		{"city2name":"晋安区"},
		{"city2name":"连江县"},
		{"city2name":"罗源县"},
		{"city2name":"马尾区"},
		{"city2name":"闽侯县"},
		{"city2name":"闽清县"},
		{"city2name":"平潭县"},
		{"city2name":"台江区"},
		{"city2name":"永泰县"}	]},
	{"city1name":"龙岩市","city2":[
		{"city2name":"长汀县"},
		{"city2name":"连城县"},
		{"city2name":"龙岩市"},
		{"city2name":"上杭县"},
		{"city2name":"武平县"},
		{"city2name":"新罗区"},
		{"city2name":"永定县"},
		{"city2name":"漳平市"}	]},
	{"city1name":"南平市","city2":[
		{"city2name":"光泽县"},
		{"city2name":"建瓯市"},
		{"city2name":"建阳市"},
		{"city2name":"南平市"},
		{"city2name":"浦城县"},
		{"city2name":"邵武市"},
		{"city2name":"顺昌县"},
		{"city2name":"松溪县"},
		{"city2name":"武夷山市"},
		{"city2name":"延平区"},
		{"city2name":"政和县"}	]},
	{"city1name":"宁德市","city2":[
		{"city2name":"福安市"},
		{"city2name":"福鼎市"},
		{"city2name":"古田县"},
		{"city2name":"蕉城区"},
		{"city2name":"宁德市"},
		{"city2name":"屏南县"},
		{"city2name":"寿宁县"},
		{"city2name":"霞浦县"},
		{"city2name":"柘荣县"},
		{"city2name":"周宁县"}	]},
	{"city1name":"莆田市","city2":[
		{"city2name":"城厢区"},
		{"city2name":"涵江区"},
		{"city2name":"荔城区"},
		{"city2name":"莆田市"},
		{"city2name":"仙游县"},
		{"city2name":"秀屿区"}	]},
	{"city1name":"秦屿","city2":[
		{"city2name":"秦屿"}	]},
	{"city1name":"泉州市","city2":[
		{"city2name":"安溪县"},
		{"city2name":"德化县"},
		{"city2name":"丰泽区"},
		{"city2name":"惠安县"},
		{"city2name":"金门县"},
		{"city2name":"晋江市"},
		{"city2name":"鲤城区"},
		{"city2name":"洛江区"},
		{"city2name":"南安市"},
		{"city2name":"泉港区"},
		{"city2name":"泉州市"},
		{"city2name":"石狮市"},
		{"city2name":"永春县"}	]},
	{"city1name":"三明市","city2":[
		{"city2name":"大田县"},
		{"city2name":"建宁县"},
		{"city2name":"将乐县"},
		{"city2name":"梅列区"},
		{"city2name":"明溪县"},
		{"city2name":"宁化县"},
		{"city2name":"清流县"},
		{"city2name":"三明市"},
		{"city2name":"三元区"},
		{"city2name":"沙县"},
		{"city2name":"泰宁县"},
		{"city2name":"永安市"},
		{"city2name":"尤溪县"}	]},
	{"city1name":"厦门市","city2":[
		{"city2name":"鼓浪屿区"},
		{"city2name":"湖里区"},
		{"city2name":"集美区"},
		{"city2name":"开元区"},
		{"city2name":"思明区"},
		{"city2name":"同安区"},
		{"city2name":"厦门市"},
		{"city2name":"杏林区"}	]},
	{"city1name":"漳州市","city2":[
		{"city2name":"长泰县"},
		{"city2name":"东山县"},
		{"city2name":"华安县"},
		{"city2name":"龙海市"},
		{"city2name":"龙文区"},
		{"city2name":"南靖县"},
		{"city2name":"平和县"},
		{"city2name":"芗城区"},
		{"city2name":"云霄县"},
		{"city2name":"漳浦县"},
		{"city2name":"漳州市"},
		{"city2name":"诏安县"}	]} ]},
{"provname":"甘肃","zone":"西北","city1":[
	{"city1name":"白银市","city2":[
		{"city2name":"白银区"},
		{"city2name":"白银市"},
		{"city2name":"会宁县"},
		{"city2name":"景泰县"},
		{"city2name":"靖远县"},
		{"city2name":"平川区"}	]},
	{"city1name":"定西地区","city2":[
		{"city2name":"定西地区"},
		{"city2name":"定西县"},
		{"city2name":"临洮县"},
		{"city2name":"陇西县"},
		{"city2name":"岷县"},
		{"city2name":"通渭县"},
		{"city2name":"渭源县"},
		{"city2name":"漳县"}	]},
	{"city1name":"甘南州","city2":[
		{"city2name":"迭部县"},
		{"city2name":"甘南州"},
		{"city2name":"合作市"},
		{"city2name":"临潭县"},
		{"city2name":"碌曲县"},
		{"city2name":"玛曲县"},
		{"city2name":"夏河县"},
		{"city2name":"舟曲县"},
		{"city2name":"卓尼县"}	]},
	{"city1name":"嘉峪关市","city2":[
		{"city2name":"嘉峪关市"}	]},
	{"city1name":"金昌市","city2":[
		{"city2name":"金昌市"},
		{"city2name":"金川区"},
		{"city2name":"永昌县"}	]},
	{"city1name":"酒泉市","city2":[
		{"city2name":"阿克塞哈萨克族自治县"},
		{"city2name":"安西县"},
		{"city2name":"敦煌市"},
		{"city2name":"金塔县"},
		{"city2name":"酒泉市"},
		{"city2name":"肃北蒙古族自治县"},
		{"city2name":"肃州区"},
		{"city2name":"玉门市"}	]},
	{"city1name":"兰州市","city2":[
		{"city2name":"安宁区"},
		{"city2name":"城关区"},
		{"city2name":"皋兰县"},
		{"city2name":"红古区"},
		{"city2name":"兰州市"},
		{"city2name":"七里河区"},
		{"city2name":"西固区"},
		{"city2name":"永登县"},
		{"city2name":"榆中县"}	]},
	{"city1name":"临夏州","city2":[
		{"city2name":"东乡族自治县"},
		{"city2name":"广河县"},
		{"city2name":"和政县"},
		{"city2name":"积石山保安族东乡族撒拉族自治县"},
		{"city2name":"康乐县"},
		{"city2name":"临夏市"},
		{"city2name":"临夏县"},
		{"city2name":"临夏州"},
		{"city2name":"永靖县"}	]},
	{"city1name":"陇南地区","city2":[
		{"city2name":"成县"},
		{"city2name":"宕昌县"},
		{"city2name":"徽县"},
		{"city2name":"康县"},
		{"city2name":"礼县"},
		{"city2name":"两当县"},
		{"city2name":"陇南地区"},
		{"city2name":"文县"},
		{"city2name":"武都县"},
		{"city2name":"西和县"}	]},
	{"city1name":"平凉市","city2":[
		{"city2name":"崇信县"},
		{"city2name":"华亭县"},
		{"city2name":"泾川县"},
		{"city2name":"静宁县"},
		{"city2name":"崆峒区"},
		{"city2name":"灵台县"},
		{"city2name":"平凉市"},
		{"city2name":"庄浪县"}	]},
	{"city1name":"庆阳市","city2":[
		{"city2name":"合水县"},
		{"city2name":"华池县"},
		{"city2name":"环县"},
		{"city2name":"宁县"},
		{"city2name":"庆城县"},
		{"city2name":"庆阳市"},
		{"city2name":"西峰区"},
		{"city2name":"镇原县"},
		{"city2name":"正宁县"}	]},
	{"city1name":"天水市","city2":[
		{"city2name":"北道区"},
		{"city2name":"甘谷县"},
		{"city2name":"秦安县"},
		{"city2name":"秦城区"},
		{"city2name":"清水县"},
		{"city2name":"天水市"},
		{"city2name":"武山县"},
		{"city2name":"张家川回族自治县"}	]},
	{"city1name":"武威市","city2":[
		{"city2name":"古浪县"},
		{"city2name":"凉州区"},
		{"city2name":"民勤县"},
		{"city2name":"天祝藏族自治县"},
		{"city2name":"武威市"}	]},
	{"city1name":"张掖市","city2":[
		{"city2name":"甘州区"},
		{"city2name":"高台县"},
		{"city2name":"临泽县"},
		{"city2name":"民乐县"},
		{"city2name":"山丹县"},
		{"city2name":"肃南裕固族自治县"},
		{"city2name":"张掖市"}	]} ]},
{"provname":"广东","zone":"华南","city1":[
	{"city1name":"潮州市","city2":[
		{"city2name":"潮安县"},
		{"city2name":"潮州市"},
		{"city2name":"饶平县"},
		{"city2name":"湘桥区"}	]},
	{"city1name":"东莞市","city2":[
		{"city2name":"东莞市"}	]},
	{"city1name":"佛山市","city2":[
		{"city2name":"禅城区"},
		{"city2name":"佛山市"},
		{"city2name":"高明区"},
		{"city2name":"南海区"},
		{"city2name":"三水区"},
		{"city2name":"顺德区"}	]},
	{"city1name":"广州市","city2":[
		{"city2name":"白云区"},
		{"city2name":"从化市"},
		{"city2name":"东山区"},
		{"city2name":"番禺区"},
		{"city2name":"芳村区"},
		{"city2name":"广州市"},
		{"city2name":"海珠区"},
		{"city2name":"花都区"},
		{"city2name":"黄埔区"},
		{"city2name":"荔湾区"},
		{"city2name":"天河区"},
		{"city2name":"越秀区"},
		{"city2name":"增城市"}	]},
	{"city1name":"河源市","city2":[
		{"city2name":"东源县"},
		{"city2name":"和平县"},
		{"city2name":"河源市"},
		{"city2name":"连平县"},
		{"city2name":"龙川县"},
		{"city2name":"源城区"},
		{"city2name":"紫金县"}	]},
	{"city1name":"惠州市","city2":[
		{"city2name":"博罗县"},
		{"city2name":"惠城区"},
		{"city2name":"惠东县"},
		{"city2name":"惠阳市"},
		{"city2name":"惠州市"},
		{"city2name":"龙门县"}	]},
	{"city1name":"江门市","city2":[
		{"city2name":"恩平市"},
		{"city2name":"鹤山市"},
		{"city2name":"江海区"},
		{"city2name":"江门市"},
		{"city2name":"开平市"},
		{"city2name":"蓬江区"},
		{"city2name":"台山市"},
		{"city2name":"新会区"}	]},
	{"city1name":"揭阳市","city2":[
		{"city2name":"惠来县"},
		{"city2name":"揭东县"},
		{"city2name":"揭西县"},
		{"city2name":"揭阳市"},
		{"city2name":"普宁市"},
		{"city2name":"榕城区"}	]},
	{"city1name":"茂名市","city2":[
		{"city2name":"电白县"},
		{"city2name":"高州市"},
		{"city2name":"化州市"},
		{"city2name":"茂港区"},
		{"city2name":"茂名市"},
		{"city2name":"茂南区"},
		{"city2name":"信宜市"}	]},
	{"city1name":"梅州市","city2":[
		{"city2name":"大埔县"},
		{"city2name":"丰顺县"},
		{"city2name":"蕉岭县"},
		{"city2name":"梅江区"},
		{"city2name":"梅县"},
		{"city2name":"梅州市"},
		{"city2name":"平远县"},
		{"city2name":"五华县"},
		{"city2name":"兴宁市"}	]},
	{"city1name":"清远市","city2":[
		{"city2name":"佛冈县"},
		{"city2name":"连南瑶族自治县"},
		{"city2name":"连山壮族瑶族自治县"},
		{"city2name":"连州市"},
		{"city2name":"清城区"},
		{"city2name":"清新县"},
		{"city2name":"清远市"},
		{"city2name":"阳山县"},
		{"city2name":"英德市"}	]},
	{"city1name":"汕头市","city2":[
		{"city2name":"潮阳市"},
		{"city2name":"澄海市"},
		{"city2name":"达濠区"},
		{"city2name":"河浦区"},
		{"city2name":"金园区"},
		{"city2name":"龙湖区"},
		{"city2name":"南澳县"},
		{"city2name":"汕头市"},
		{"city2name":"升平区"}	]},
	{"city1name":"汕尾市","city2":[
		{"city2name":"城区"},
		{"city2name":"海丰县"},
		{"city2name":"陆丰市"},
		{"city2name":"陆河县"},
		{"city2name":"汕尾市"}	]},
	{"city1name":"韶关市","city2":[
		{"city2name":"北江区"},
		{"city2name":"乐昌市"},
		{"city2name":"南雄市"},
		{"city2name":"曲江县"},
		{"city2name":"仁化县"},
		{"city2name":"乳源瑶族自治县"},
		{"city2name":"韶关市"},
		{"city2name":"始兴县"},
		{"city2name":"翁源县"},
		{"city2name":"武江区"},
		{"city2name":"新丰县"},
		{"city2name":"浈江区"}	]},
	{"city1name":"深圳市","city2":[
		{"city2name":"宝安区"},
		{"city2name":"福田区"},
		{"city2name":"龙岗区"},
		{"city2name":"罗湖区"},
		{"city2name":"南山区"},
		{"city2name":"深圳市"},
		{"city2name":"盐田区"}	]},
	{"city1name":"阳江市","city2":[
		{"city2name":"江城区"},
		{"city2name":"阳春市"},
		{"city2name":"阳东县"},
		{"city2name":"阳江市"},
		{"city2name":"阳西县"}	]},
	{"city1name":"云浮市","city2":[
		{"city2name":"罗定市"},
		{"city2name":"新兴县"},
		{"city2name":"郁南县"},
		{"city2name":"云安县"},
		{"city2name":"云城区"},
		{"city2name":"云浮市"}	]},
	{"city1name":"湛江市","city2":[
		{"city2name":"赤坎区"},
		{"city2name":"雷州市"},
		{"city2name":"廉江市"},
		{"city2name":"麻章区"},
		{"city2name":"坡头区"},
		{"city2name":"遂溪县"},
		{"city2name":"吴川市"},
		{"city2name":"霞山区"},
		{"city2name":"徐闻县"},
		{"city2name":"湛江市"}	]},
	{"city1name":"肇庆市","city2":[
		{"city2name":"德庆县"},
		{"city2name":"鼎湖区"},
		{"city2name":"端州区"},
		{"city2name":"封开县"},
		{"city2name":"高要市"},
		{"city2name":"广宁县"},
		{"city2name":"怀集县"},
		{"city2name":"四会市"},
		{"city2name":"肇庆市"}	]},
	{"city1name":"中山市","city2":[
		{"city2name":"中山市"}	]},
	{"city1name":"珠海市","city2":[
		{"city2name":"斗门区"},
		{"city2name":"金湾区"},
		{"city2name":"香洲区"},
		{"city2name":"珠海市"}	]} ]},
{"provname":"广西","zone":"华南","city1":[
	{"city1name":"百色市","city2":[
		{"city2name":"百色市"},
		{"city2name":"德保县"},
		{"city2name":"靖西县"},
		{"city2name":"乐业县"},
		{"city2name":"凌云县"},
		{"city2name":"隆林各族自治县"},
		{"city2name":"那坡县"},
		{"city2name":"平果县"},
		{"city2name":"田东县"},
		{"city2name":"田林县"},
		{"city2name":"田阳县"},
		{"city2name":"西林县"},
		{"city2name":"右江区"}	]},
	{"city1name":"北海市","city2":[
		{"city2name":"北海市"},
		{"city2name":"海城区"},
		{"city2name":"合浦县"},
		{"city2name":"铁山港区"},
		{"city2name":"银海区"}	]},
	{"city1name":"崇左市","city2":[
		{"city2name":"崇左市"},
		{"city2name":"大新县"},
		{"city2name":"扶绥县"},
		{"city2name":"江洲区"},
		{"city2name":"龙州县"},
		{"city2name":"宁明县"},
		{"city2name":"凭祥市"},
		{"city2name":"天等县"}	]},
	{"city1name":"防城港市","city2":[
		{"city2name":"东兴市"},
		{"city2name":"防城港市"},
		{"city2name":"防城区"},
		{"city2name":"港口区"},
		{"city2name":"上思县"}	]},
	{"city1name":"贵港市","city2":[
		{"city2name":"港北区"},
		{"city2name":"港南区"},
		{"city2name":"贵港市"},
		{"city2name":"桂平市"},
		{"city2name":"平南县"}	]},
	{"city1name":"桂林市","city2":[
		{"city2name":"叠彩区"},
		{"city2name":"恭城瑶族自治县"},
		{"city2name":"灌阳县"},
		{"city2name":"桂林市"},
		{"city2name":"荔浦县"},
		{"city2name":"临桂县"},
		{"city2name":"灵川县"},
		{"city2name":"龙胜各族自治县"},
		{"city2name":"平乐县"},
		{"city2name":"七星区"},
		{"city2name":"全州县"},
		{"city2name":"象山区"},
		{"city2name":"兴安县"},
		{"city2name":"秀峰区"},
		{"city2name":"雁山区"},
		{"city2name":"阳朔县"},
		{"city2name":"永福县"},
		{"city2name":"资源县"}	]},
	{"city1name":"河池市","city2":[
		{"city2name":"巴马瑶族自治县"},
		{"city2name":"大化瑶族自治县"},
		{"city2name":"东兰县"},
		{"city2name":"都安瑶族自治县"},
		{"city2name":"凤山县"},
		{"city2name":"河池市"},
		{"city2name":"环江毛南族自治县"},
		{"city2name":"金城江区"},
		{"city2name":"罗城仫佬族自治县"},
		{"city2name":"南丹县"},
		{"city2name":"天峨县"},
		{"city2name":"宜州市"}	]},
	{"city1name":"贺州市","city2":[
		{"city2name":"八步区"},
		{"city2name":"富川瑶族自治县"},
		{"city2name":"贺州市"},
		{"city2name":"昭平县"},
		{"city2name":"钟山县"}	]},
	{"city1name":"来宾市","city2":[
		{"city2name":"合山市"},
		{"city2name":"金秀瑶族自治县"},
		{"city2name":"来宾市"},
		{"city2name":"武宣县"},
		{"city2name":"象州县"},
		{"city2name":"忻城县"},
		{"city2name":"兴宾区"}	]},
	{"city1name":"柳州市","city2":[
		{"city2name":"城中区"},
		{"city2name":"柳北区"},
		{"city2name":"柳城县"},
		{"city2name":"柳江县"},
		{"city2name":"柳南区"},
		{"city2name":"柳州市"},
		{"city2name":"鹿寨县"},
		{"city2name":"融安县"},
		{"city2name":"融水苗族自治县"},
		{"city2name":"三江侗族自治县"},
		{"city2name":"鱼峰区"}	]},
	{"city1name":"南宁市","city2":[
		{"city2name":"宾阳县"},
		{"city2name":"城北区"},
		{"city2name":"横县"},
		{"city2name":"江南区"},
		{"city2name":"隆安县"},
		{"city2name":"马山县"},
		{"city2name":"南宁市"},
		{"city2name":"上林县"},
		{"city2name":"武鸣县"},
		{"city2name":"新城区"},
		{"city2name":"兴宁区"},
		{"city2name":"邕宁县"},
		{"city2name":"永新区"}	]},
	{"city1name":"钦州市","city2":[
		{"city2name":"灵山县"},
		{"city2name":"浦北县"},
		{"city2name":"钦北区"},
		{"city2name":"钦南区"},
		{"city2name":"钦州市"}	]},
	{"city1name":"梧州市","city2":[
		{"city2name":"苍梧县"},
		{"city2name":"岑溪市"},
		{"city2name":"蝶山区"},
		{"city2name":"蒙山县"},
		{"city2name":"市郊区"},
		{"city2name":"藤县"},
		{"city2name":"万秀区"},
		{"city2name":"梧州市"}	]},
	{"city1name":"玉林市","city2":[
		{"city2name":"北流市"},
		{"city2name":"博白县"},
		{"city2name":"陆川县"},
		{"city2name":"容县"},
		{"city2name":"兴业县"},
		{"city2name":"玉林市"},
		{"city2name":"玉州区"}	]} ]},
{"provname":"贵州","zone":"西南","city1":[
	{"city1name":"安顺市","city2":[
		{"city2name":"安顺市"},
		{"city2name":"关岭布依族苗族自治县"},
		{"city2name":"平坝县"},
		{"city2name":"普定县"},
		{"city2name":"西秀区"},
		{"city2name":"镇宁布依族苗族自治县"},
		{"city2name":"紫云苗族布依族自治县"}	]},
	{"city1name":"毕节地区","city2":[
		{"city2name":"毕节地区"},
		{"city2name":"毕节市"},
		{"city2name":"大方县"},
		{"city2name":"赫章县"},
		{"city2name":"金沙县"},
		{"city2name":"纳雍县"},
		{"city2name":"黔西县"},
		{"city2name":"威宁彝族回族苗族自治县"},
		{"city2name":"织金县"}	]},
	{"city1name":"贵阳市","city2":[
		{"city2name":"白云区"},
		{"city2name":"贵阳市"},
		{"city2name":"花溪区"},
		{"city2name":"开阳县"},
		{"city2name":"南明区"},
		{"city2name":"清镇市"},
		{"city2name":"乌当区"},
		{"city2name":"息烽县"},
		{"city2name":"小河区"},
		{"city2name":"修文县"},
		{"city2name":"云岩区"}	]},
	{"city1name":"六盘水市","city2":[
		{"city2name":"六盘水市"},
		{"city2name":"六枝特区"},
		{"city2name":"盘县"},
		{"city2name":"水城县"},
		{"city2name":"钟山区"}	]},
	{"city1name":"黔东南州","city2":[
		{"city2name":"岑巩县"},
		{"city2name":"从江县"},
		{"city2name":"丹寨县"},
		{"city2name":"黄平县"},
		{"city2name":"剑河县"},
		{"city2name":"锦屏县"},
		{"city2name":"凯里市"},
		{"city2name":"雷山县"},
		{"city2name":"黎平县"},
		{"city2name":"麻江县"},
		{"city2name":"黔东南州"},
		{"city2name":"榕江县"},
		{"city2name":"三穗县"},
		{"city2name":"施秉县"},
		{"city2name":"台江县"},
		{"city2name":"天柱县"},
		{"city2name":"镇远县"}	]},
	{"city1name":"黔南州","city2":[
		{"city2name":"长顺县"},
		{"city2name":"都匀市"},
		{"city2name":"独山县"},
		{"city2name":"福泉市"},
		{"city2name":"贵定县"},
		{"city2name":"惠水县"},
		{"city2name":"荔波县"},
		{"city2name":"龙里县"},
		{"city2name":"罗甸县"},
		{"city2name":"平塘县"},
		{"city2name":"黔南州"},
		{"city2name":"三都水族自治县"},
		{"city2name":"瓮安县"}	]},
	{"city1name":"黔西南州","city2":[
		{"city2name":"安龙县"},
		{"city2name":"册亨县"},
		{"city2name":"普安县"},
		{"city2name":"黔西南州"},
		{"city2name":"晴隆县"},
		{"city2name":"望谟县"},
		{"city2name":"兴仁县"},
		{"city2name":"兴义市"},
		{"city2name":"贞丰县"}	]},
	{"city1name":"铜仁地区","city2":[
		{"city2name":"德江县"},
		{"city2name":"江口县"},
		{"city2name":"石阡县"},
		{"city2name":"思南县"},
		{"city2name":"松桃苗族自治县"},
		{"city2name":"铜仁地区"},
		{"city2name":"铜仁市"},
		{"city2name":"万山特区"},
		{"city2name":"沿河土家族自治县"},
		{"city2name":"印江土家族苗族自治县"},
		{"city2name":"玉屏侗族自治县"}	]},
	{"city1name":"遵义市","city2":[
		{"city2name":"赤水市"},
		{"city2name":"道真仡佬族苗族自治县"},
		{"city2name":"凤冈县"},
		{"city2name":"红花岗区"},
		{"city2name":"湄潭县"},
		{"city2name":"仁怀市"},
		{"city2name":"绥阳县"},
		{"city2name":"桐梓县"},
		{"city2name":"务川仡佬族苗族自治县"},
		{"city2name":"习水县"},
		{"city2name":"余庆县"},
		{"city2name":"正安县"},
		{"city2name":"遵义市"},
		{"city2name":"遵义县"}	]} ]},
{"provname":"海南","zone":"华南","city1":[
	{"city1name":"白沙黎族自治县","city2":[
		{"city2name":"白沙黎族自治县"}	]},
	{"city1name":"保亭黎族苗族自治县","city2":[
		{"city2name":"保亭黎族苗族自治县"}	]},
	{"city1name":"昌江黎族自治县","city2":[
		{"city2name":"昌江黎族自治县"}	]},
	{"city1name":"澄迈县","city2":[
		{"city2name":"澄迈县"}	]},
	{"city1name":"儋州市","city2":[
		{"city2name":"儋州市"}	]},
	{"city1name":"定安县","city2":[
		{"city2name":"定安县"}	]},
	{"city1name":"东方市","city2":[
		{"city2name":"东方市"}	]},
	{"city1name":"海口市","city2":[
		{"city2name":"海口市"},
		{"city2name":"龙华区"},
		{"city2name":"美兰区"},
		{"city2name":"琼山区"},
		{"city2name":"秀英区"}	]},
	{"city1name":"乐东黎族自治县","city2":[
		{"city2name":"乐东黎族自治县"}	]},
	{"city1name":"临高县","city2":[
		{"city2name":"临高县"}	]},
	{"city1name":"陵水黎族自治县","city2":[
		{"city2name":"陵水黎族自治县"}	]},
	{"city1name":"南沙群岛","city2":[
		{"city2name":"南沙群岛"}	]},
	{"city1name":"琼海市","city2":[
		{"city2name":"琼海市"}	]},
	{"city1name":"琼中黎族苗族自治县","city2":[
		{"city2name":"琼中黎族苗族自治县"}	]},
	{"city1name":"三亚市","city2":[
		{"city2name":"三亚市"}	]},
	{"city1name":"屯昌县","city2":[
		{"city2name":"屯昌县"}	]},
	{"city1name":"万宁市","city2":[
		{"city2name":"万宁市"}	]},
	{"city1name":"文昌市","city2":[
		{"city2name":"文昌市"}	]},
	{"city1name":"五指山市","city2":[
		{"city2name":"五指山市"}	]},
	{"city1name":"西沙群岛","city2":[
		{"city2name":"西沙群岛"}	]},
	{"city1name":"中沙群岛的岛礁及其海域","city2":[
		{"city2name":"中沙群岛的岛礁及其海域"}	]} ]},
{"provname":"河北","zone":"华北","city1":[
	{"city1name":"保定市","city2":[
		{"city2name":"安国市"},
		{"city2name":"安新县"},
		{"city2name":"保定市"},
		{"city2name":"北市区"},
		{"city2name":"博野县"},
		{"city2name":"定兴县"},
		{"city2name":"定州市"},
		{"city2name":"阜平县"},
		{"city2name":"高碑店市"},
		{"city2name":"高阳县"},
		{"city2name":"涞水县"},
		{"city2name":"涞源县"},
		{"city2name":"蠡县"},
		{"city2name":"满城县"},
		{"city2name":"南市区"},
		{"city2name":"清苑县"},
		{"city2name":"曲阳县"},
		{"city2name":"容城县"},
		{"city2name":"顺平县"},
		{"city2name":"唐县"},
		{"city2name":"望都县"},
		{"city2name":"新市区"},
		{"city2name":"雄县"},
		{"city2name":"徐水县"},
		{"city2name":"易县"},
		{"city2name":"涿州市"}	]},
	{"city1name":"沧州市","city2":[
		{"city2name":"泊头市"},
		{"city2name":"沧县"},
		{"city2name":"沧州市"},
		{"city2name":"东光县"},
		{"city2name":"海兴县"},
		{"city2name":"河间市"},
		{"city2name":"黄骅市"},
		{"city2name":"孟村回族自治县"},
		{"city2name":"南皮县"},
		{"city2name":"青县"},
		{"city2name":"任丘市"},
		{"city2name":"肃宁县"},
		{"city2name":"吴桥县"},
		{"city2name":"献县"},
		{"city2name":"盐山县"},
		{"city2name":"运河区"}	]},
	{"city1name":"承德市","city2":[
		{"city2name":"承德市"},
		{"city2name":"承德县"},
		{"city2name":"丰宁满族自治县"},
		{"city2name":"宽城满族自治县"},
		{"city2name":"隆化县"},
		{"city2name":"滦平县"},
		{"city2name":"平泉县"},
		{"city2name":"双滦区"},
		{"city2name":"双桥区"},
		{"city2name":"围场满族蒙古族自治县"},
		{"city2name":"兴隆县"},
		{"city2name":"鹰手营子矿区"}	]},
	{"city1name":"邯郸市","city2":[
		{"city2name":"成安县"},
		{"city2name":"磁县"},
		{"city2name":"丛台区"},
		{"city2name":"大名县"},
		{"city2name":"肥乡县"},
		{"city2name":"峰峰矿区"},
		{"city2name":"复兴区"},
		{"city2name":"馆陶县"},
		{"city2name":"广平县"},
		{"city2name":"邯郸市"},
		{"city2name":"邯郸县"},
		{"city2name":"邯山区"},
		{"city2name":"鸡泽县"},
		{"city2name":"临漳县"},
		{"city2name":"邱县"},
		{"city2name":"曲周县"},
		{"city2name":"涉县"},
		{"city2name":"魏县"},
		{"city2name":"武安市"},
		{"city2name":"永年县"}	]},
	{"city1name":"衡水市","city2":[
		{"city2name":"安平县"},
		{"city2name":"阜城县"},
		{"city2name":"故城县"},
		{"city2name":"衡水市"},
		{"city2name":"冀州市"},
		{"city2name":"景县"},
		{"city2name":"饶阳县"},
		{"city2name":"深州市"},
		{"city2name":"桃城区"},
		{"city2name":"武强县"},
		{"city2name":"武邑县"},
		{"city2name":"枣强县"}	]},
	{"city1name":"廊坊市","city2":[
		{"city2name":"安次区"},
		{"city2name":"霸州市"},
		{"city2name":"大厂回族自治县"},
		{"city2name":"大城县"},
		{"city2name":"固安县"},
		{"city2name":"广阳区"},
		{"city2name":"廊坊市"},
		{"city2name":"三河市"},
		{"city2name":"文安县"},
		{"city2name":"香河县"},
		{"city2name":"永清县"}	]},
	{"city1name":"秦皇岛市","city2":[
		{"city2name":"北戴河区"},
		{"city2name":"昌黎县"},
		{"city2name":"抚宁县"},
		{"city2name":"海港区"},
		{"city2name":"卢龙县"},
		{"city2name":"秦皇岛市"},
		{"city2name":"青龙满族自治县"},
		{"city2name":"山海关区"}	]},
	{"city1name":"石家庄市","city2":[
		{"city2name":"长安区"},
		{"city2name":"高邑县"},
		{"city2name":"藁城市"},
		{"city2name":"晋州市"},
		{"city2name":"井陉矿区"},
		{"city2name":"井陉县"},
		{"city2name":"灵寿县"},
		{"city2name":"鹿泉市"},
		{"city2name":"栾城县"},
		{"city2name":"平山县"},
		{"city2name":"桥东区"},
		{"city2name":"桥西区"},
		{"city2name":"深泽县"},
		{"city2name":"石家庄市"},
		{"city2name":"无极县"},
		{"city2name":"辛集市"},
		{"city2name":"新华区"},
		{"city2name":"新乐市"},
		{"city2name":"行唐县"},
		{"city2name":"裕华区"},
		{"city2name":"元氏县"},
		{"city2name":"赞皇县"},
		{"city2name":"赵县"},
		{"city2name":"正定县"}	]},
	{"city1name":"唐山市","city2":[
		{"city2name":"丰南区"},
		{"city2name":"丰润区"},
		{"city2name":"古冶区"},
		{"city2name":"开平区"},
		{"city2name":"乐亭县"},
		{"city2name":"路北区"},
		{"city2name":"路南区"},
		{"city2name":"滦南县"},
		{"city2name":"滦县"},
		{"city2name":"迁安市"},
		{"city2name":"迁西县"},
		{"city2name":"唐海县"},
		{"city2name":"唐山市"},
		{"city2name":"玉田县"},
		{"city2name":"遵化市"}	]},
	{"city1name":"邢台市","city2":[
		{"city2name":"柏乡县"},
		{"city2name":"广宗县"},
		{"city2name":"巨鹿县"},
		{"city2name":"临城县"},
		{"city2name":"临西县"},
		{"city2name":"隆尧县"},
		{"city2name":"内丘县"},
		{"city2name":"南宫市"},
		{"city2name":"南和县"},
		{"city2name":"宁晋县"},
		{"city2name":"平乡县"},
		{"city2name":"清河县"},
		{"city2name":"任县"},
		{"city2name":"沙河市"},
		{"city2name":"威县"},
		{"city2name":"新河县"},
		{"city2name":"邢台市"},
		{"city2name":"邢台县"}	]},
	{"city1name":"张家口市","city2":[
		{"city2name":"赤城县"},
		{"city2name":"崇礼县"},
		{"city2name":"沽源县"},
		{"city2name":"怀安县"},
		{"city2name":"怀来县"},
		{"city2name":"康保县"},
		{"city2name":"尚义县"},
		{"city2name":"万全县"},
		{"city2name":"蔚县"},
		{"city2name":"下花园区"},
		{"city2name":"宣化区"},
		{"city2name":"宣化县"},
		{"city2name":"阳原县"},
		{"city2name":"张北县"},
		{"city2name":"张家口市"},
		{"city2name":"涿鹿县"}	]} ]},
{"provname":"河南","zone":"华中","city1":[
	{"city1name":"安阳市","city2":[
		{"city2name":"安阳市"},
		{"city2name":"安阳县"},
		{"city2name":"北关区"},
		{"city2name":"滑县"},
		{"city2name":"林州市"},
		{"city2name":"龙安区"},
		{"city2name":"内黄县"},
		{"city2name":"汤阴县"},
		{"city2name":"文峰区"},
		{"city2name":"殷都区"}	]},
	{"city1name":"鹤壁市","city2":[
		{"city2name":"鹤壁市"},
		{"city2name":"鹤山区"},
		{"city2name":"浚县"},
		{"city2name":"淇滨区"},
		{"city2name":"淇县"},
		{"city2name":"山城区"}	]},
	{"city1name":"济源市","city2":[
		{"city2name":"济源市"}	]},
	{"city1name":"焦作市","city2":[
		{"city2name":"博爱县"},
		{"city2name":"焦作市"},
		{"city2name":"解放区"},
		{"city2name":"马村区"},
		{"city2name":"孟州市"},
		{"city2name":"沁阳市"},
		{"city2name":"山阳区"},
		{"city2name":"温县"},
		{"city2name":"武陟县"},
		{"city2name":"修武县"},
		{"city2name":"中站区"}	]},
	{"city1name":"开封市","city2":[
		{"city2name":"鼓楼区"},
		{"city2name":"郊区"},
		{"city2name":"开封市"},
		{"city2name":"开封县"},
		{"city2name":"兰考县"},
		{"city2name":"龙亭区"},
		{"city2name":"南关区"},
		{"city2name":"杞县"},
		{"city2name":"顺河回族区"},
		{"city2name":"通许县"},
		{"city2name":"尉氏县"}	]},
	{"city1name":"洛阳市","city2":[
		{"city2name":"瀍河回族区"},
		{"city2name":"吉利区"},
		{"city2name":"涧西区"},
		{"city2name":"老城区"},
		{"city2name":"栾川县"},
		{"city2name":"洛龙区"},
		{"city2name":"洛宁县"},
		{"city2name":"洛阳市"},
		{"city2name":"孟津县"},
		{"city2name":"汝阳县"},
		{"city2name":"嵩县"},
		{"city2name":"西工区"},
		{"city2name":"新安县"},
		{"city2name":"偃师市"},
		{"city2name":"伊川县"},
		{"city2name":"宜阳县"}	]},
	{"city1name":"漯河市","city2":[
		{"city2name":"临颍县"},
		{"city2name":"漯河市"},
		{"city2name":"舞阳县"},
		{"city2name":"郾城县"},
		{"city2name":"源汇区"}	]},
	{"city1name":"南阳市","city2":[
		{"city2name":"邓州市"},
		{"city2name":"方城县"},
		{"city2name":"内乡县"},
		{"city2name":"南阳市"},
		{"city2name":"南召县"},
		{"city2name":"社旗县"},
		{"city2name":"唐河县"},
		{"city2name":"桐柏县"},
		{"city2name":"宛城区"},
		{"city2name":"卧龙区"},
		{"city2name":"西峡县"},
		{"city2name":"淅川县"},
		{"city2name":"新野县"},
		{"city2name":"镇平县"}	]},
	{"city1name":"平顶山市","city2":[
		{"city2name":"宝丰县"},
		{"city2name":"郏县"},
		{"city2name":"鲁山县"},
		{"city2name":"平顶山市"},
		{"city2name":"汝州市"},
		{"city2name":"石龙区"},
		{"city2name":"卫东区"},
		{"city2name":"舞钢市"},
		{"city2name":"新华区"},
		{"city2name":"叶县"},
		{"city2name":"湛河区"}	]},
	{"city1name":"濮阳市","city2":[
		{"city2name":"范县"},
		{"city2name":"华龙区"},
		{"city2name":"南乐县"},
		{"city2name":"濮阳市"},
		{"city2name":"濮阳县"},
		{"city2name":"清丰县"},
		{"city2name":"台前县"}	]},
	{"city1name":"三门峡市","city2":[
		{"city2name":"湖滨区"},
		{"city2name":"灵宝市"},
		{"city2name":"卢氏县"},
		{"city2name":"三门峡市"},
		{"city2name":"陕县"},
		{"city2name":"渑池县"},
		{"city2name":"义马市"}	]},
	{"city1name":"商丘市","city2":[
		{"city2name":"梁园区"},
		{"city2name":"民权县"},
		{"city2name":"宁陵县"},
		{"city2name":"商丘市"},
		{"city2name":"睢县"},
		{"city2name":"睢阳区"},
		{"city2name":"夏邑县"},
		{"city2name":"永城市"},
		{"city2name":"虞城县"},
		{"city2name":"柘城县"}	]},
	{"city1name":"新乡市","city2":[
		{"city2name":"北站区"},
		{"city2name":"长垣县"},
		{"city2name":"封丘县"},
		{"city2name":"红旗区"},
		{"city2name":"辉县市"},
		{"city2name":"获嘉县"},
		{"city2name":"卫辉市"},
		{"city2name":"新乡市"},
		{"city2name":"新乡县"},
		{"city2name":"延津县"},
		{"city2name":"原阳县"}	]},
	{"city1name":"信阳市","city2":[
		{"city2name":"固始县"},
		{"city2name":"光山县"},
		{"city2name":"淮滨县"},
		{"city2name":"潢川县"},
		{"city2name":"罗山县"},
		{"city2name":"平桥区"},
		{"city2name":"商城县"},
		{"city2name":"浉河区"},
		{"city2name":"息县"},
		{"city2name":"新县"},
		{"city2name":"信阳市"}	]},
	{"city1name":"许昌市","city2":[
		{"city2name":"长葛市"},
		{"city2name":"魏都区"},
		{"city2name":"襄城县"},
		{"city2name":"许昌市"},
		{"city2name":"许昌县"},
		{"city2name":"鄢陵县"},
		{"city2name":"禹州市"}	]},
	{"city1name":"郑州市","city2":[
		{"city2name":"登封市"},
		{"city2name":"二七区"},
		{"city2name":"巩义市"},
		{"city2name":"管城回族区"},
		{"city2name":"金水区"},
		{"city2name":"邙山区"},
		{"city2name":"上街区"},
		{"city2name":"新密市"},
		{"city2name":"新郑市"},
		{"city2name":"荥阳市"},
		{"city2name":"郑州市"},
		{"city2name":"中牟县"},
		{"city2name":"中原区"}	]},
	{"city1name":"周口市","city2":[
		{"city2name":"川汇区"},
		{"city2name":"郸城县"},
		{"city2name":"扶沟县"},
		{"city2name":"淮阳县"},
		{"city2name":"鹿邑县"},
		{"city2name":"商水县"},
		{"city2name":"沈丘县"},
		{"city2name":"太康县"},
		{"city2name":"西华县"},
		{"city2name":"项城市"},
		{"city2name":"周口市"}	]},
	{"city1name":"驻马店市","city2":[
		{"city2name":"泌阳县"},
		{"city2name":"平舆县"},
		{"city2name":"确山县"},
		{"city2name":"汝南县"},
		{"city2name":"上蔡县"},
		{"city2name":"遂平县"},
		{"city2name":"西平县"},
		{"city2name":"新蔡县"},
		{"city2name":"驿城区"},
		{"city2name":"正阳县"},
		{"city2name":"驻马店市"}	]} ]},
{"provname":"黑龙江","zone":"东北","city1":[
	{"city1name":"大庆市","city2":[
		{"city2name":"大庆市"},
		{"city2name":"大同区"},
		{"city2name":"杜尔伯特蒙古族自治县"},
		{"city2name":"红岗区"},
		{"city2name":"林甸县"},
		{"city2name":"龙凤区"},
		{"city2name":"让胡路区"},
		{"city2name":"萨尔图区"},
		{"city2name":"肇源县"},
		{"city2name":"肇州县"}	]},
	{"city1name":"大兴安岭地区","city2":[
		{"city2name":"大兴安岭地区"},
		{"city2name":"呼玛县"},
		{"city2name":"漠河县"},
		{"city2name":"塔河县"}	]},
	{"city1name":"哈尔滨市","city2":[
		{"city2name":"阿城市"},
		{"city2name":"巴彦县"},
		{"city2name":"宾县"},
		{"city2name":"道里区"},
		{"city2name":"道外区"},
		{"city2name":"动力区"},
		{"city2name":"方正县"},
		{"city2name":"哈尔滨市"},
		{"city2name":"呼兰县"},
		{"city2name":"木兰县"},
		{"city2name":"南岗区"},
		{"city2name":"平房区"},
		{"city2name":"尚志市"},
		{"city2name":"双城市"},
		{"city2name":"太平区"},
		{"city2name":"通河县"},
		{"city2name":"五常市"},
		{"city2name":"香坊区"},
		{"city2name":"延寿县"},
		{"city2name":"依兰县"}	]},
	{"city1name":"鹤岗市","city2":[
		{"city2name":"东山区"},
		{"city2name":"工农区"},
		{"city2name":"鹤岗市"},
		{"city2name":"萝北县"},
		{"city2name":"南山区"},
		{"city2name":"绥滨县"},
		{"city2name":"向阳区"},
		{"city2name":"兴安区"},
		{"city2name":"兴山区"}	]},
	{"city1name":"黑河市","city2":[
		{"city2name":"爱辉区"},
		{"city2name":"北安市"},
		{"city2name":"黑河市"},
		{"city2name":"嫩江县"},
		{"city2name":"孙吴县"},
		{"city2name":"五大连池市"},
		{"city2name":"逊克县"}	]},
	{"city1name":"鸡西市","city2":[
		{"city2name":"城子河区"},
		{"city2name":"滴道区"},
		{"city2name":"恒山区"},
		{"city2name":"虎林市"},
		{"city2name":"鸡东县"},
		{"city2name":"鸡冠区"},
		{"city2name":"鸡西市"},
		{"city2name":"梨树区"},
		{"city2name":"麻山区"},
		{"city2name":"密山市"}	]},
	{"city1name":"佳木斯市","city2":[
		{"city2name":"东风区"},
		{"city2name":"抚远县"},
		{"city2name":"富锦市"},
		{"city2name":"桦川县"},
		{"city2name":"桦南县"},
		{"city2name":"佳木斯市"},
		{"city2name":"郊区"},
		{"city2name":"前进区"},
		{"city2name":"汤原县"},
		{"city2name":"同江市"},
		{"city2name":"永红区"}	]},
	{"city1name":"牡丹江市","city2":[
		{"city2name":"爱民区"},
		{"city2name":"东安区"},
		{"city2name":"东宁县"},
		{"city2name":"海林市"},
		{"city2name":"林口县"},
		{"city2name":"牡丹江市"},
		{"city2name":"穆棱市"},
		{"city2name":"宁安市"},
		{"city2name":"绥芬河市"},
		{"city2name":"西安区"},
		{"city2name":"阳明区"}	]},
	{"city1name":"七台河市","city2":[
		{"city2name":"勃利县"},
		{"city2name":"七台河市"},
		{"city2name":"茄子河区"},
		{"city2name":"桃山区"},
		{"city2name":"新兴区"}	]},
	{"city1name":"齐齐哈尔市","city2":[
		{"city2name":"昂昂溪区"},
		{"city2name":"拜泉县"},
		{"city2name":"富拉尔基区"},
		{"city2name":"富裕县"},
		{"city2name":"甘南县"},
		{"city2name":"建华区"},
		{"city2name":"克东县"},
		{"city2name":"克山县"},
		{"city2name":"龙江县"},
		{"city2name":"龙沙区"},
		{"city2name":"梅里斯达斡尔族区"},
		{"city2name":"讷河市"},
		{"city2name":"碾子山区"},
		{"city2name":"齐齐哈尔市"},
		{"city2name":"泰来县"},
		{"city2name":"铁锋区"},
		{"city2name":"依安县"}	]},
	{"city1name":"双鸭山市","city2":[
		{"city2name":"宝清县"},
		{"city2name":"宝山区"},
		{"city2name":"集贤县"},
		{"city2name":"尖山区"},
		{"city2name":"岭东区"},
		{"city2name":"饶河县"},
		{"city2name":"双鸭山市"},
		{"city2name":"四方台区"},
		{"city2name":"友谊县"}	]},
	{"city1name":"绥化市","city2":[
		{"city2name":"安达市"},
		{"city2name":"北林区"},
		{"city2name":"海伦市"},
		{"city2name":"兰西县"},
		{"city2name":"明水县"},
		{"city2name":"青冈县"},
		{"city2name":"庆安县"},
		{"city2name":"绥化市"},
		{"city2name":"绥棱县"},
		{"city2name":"望奎县"},
		{"city2name":"肇东市"}	]},
	{"city1name":"伊春市","city2":[
		{"city2name":"翠峦区"},
		{"city2name":"带岭区"},
		{"city2name":"红星区"},
		{"city2name":"嘉荫县"},
		{"city2name":"金山屯区"},
		{"city2name":"美溪区"},
		{"city2name":"南岔区"},
		{"city2name":"上甘岭区"},
		{"city2name":"汤旺河区"},
		{"city2name":"铁力市"},
		{"city2name":"乌马河区"},
		{"city2name":"乌伊岭区"},
		{"city2name":"五营区"},
		{"city2name":"西林区"},
		{"city2name":"新青区"},
		{"city2name":"伊春区"},
		{"city2name":"伊春市"},
		{"city2name":"友好区"}	]} ]},
{"provname":"湖北","zone":"华中","city1":[
	{"city1name":"鄂州市","city2":[
		{"city2name":"鄂城区"},
		{"city2name":"鄂州市"},
		{"city2name":"华容区"},
		{"city2name":"梁子湖区"}	]},
	{"city1name":"恩施州","city2":[
		{"city2name":"巴东县"},
		{"city2name":"恩施市"},
		{"city2name":"恩施州"},
		{"city2name":"鹤峰县"},
		{"city2name":"建始县"},
		{"city2name":"来凤县"},
		{"city2name":"利川市"},
		{"city2name":"咸丰县"},
		{"city2name":"宣恩县"}	]},
	{"city1name":"黄冈市","city2":[
		{"city2name":"红安县"},
		{"city2name":"黄冈市"},
		{"city2name":"黄梅县"},
		{"city2name":"黄州区"},
		{"city2name":"罗田县"},
		{"city2name":"麻城市"},
		{"city2name":"蕲春县"},
		{"city2name":"团风县"},
		{"city2name":"武穴市"},
		{"city2name":"浠水县"},
		{"city2name":"英山县"}	]},
	{"city1name":"黄石市","city2":[
		{"city2name":"大冶市"},
		{"city2name":"黄石港区"},
		{"city2name":"黄石市"},
		{"city2name":"铁山区"},
		{"city2name":"西塞山区"},
		{"city2name":"下陆区"},
		{"city2name":"阳新县"}	]},
	{"city1name":"荆门市","city2":[
		{"city2name":"东宝区"},
		{"city2name":"掇刀区"},
		{"city2name":"京山县"},
		{"city2name":"荆门市"},
		{"city2name":"沙洋县"},
		{"city2name":"钟祥市"}	]},
	{"city1name":"荆州市","city2":[
		{"city2name":"公安县"},
		{"city2name":"洪湖市"},
		{"city2name":"监利县"},
		{"city2name":"江陵县"},
		{"city2name":"荆州区"},
		{"city2name":"荆州市"},
		{"city2name":"沙市区"},
		{"city2name":"石首市"},
		{"city2name":"松滋市"}	]},
	{"city1name":"潜江市","city2":[
		{"city2name":"潜江市"}	]},
	{"city1name":"神农架林区","city2":[
		{"city2name":"神农架林区"}	]},
	{"city1name":"十堰市","city2":[
		{"city2name":"丹江口市"},
		{"city2name":"房县"},
		{"city2name":"茅箭区"},
		{"city2name":"十堰市"},
		{"city2name":"郧西县"},
		{"city2name":"郧县"},
		{"city2name":"张湾区"},
		{"city2name":"竹山县"},
		{"city2name":"竹溪县"}	]},
	{"city1name":"随州市","city2":[
		{"city2name":"广水市"},
		{"city2name":"随州市"},
		{"city2name":"曾都区"}	]},
	{"city1name":"天门市","city2":[
		{"city2name":"天门市"}	]},
	{"city1name":"武汉市","city2":[
		{"city2name":"蔡甸区"},
		{"city2name":"东西湖区"},
		{"city2name":"汉南区"},
		{"city2name":"汉阳区"},
		{"city2name":"洪山区"},
		{"city2name":"黄陂区"},
		{"city2name":"江岸区"},
		{"city2name":"江汉区"},
		{"city2name":"江夏区"},
		{"city2name":"硚口区"},
		{"city2name":"青山区"},
		{"city2name":"武昌区"},
		{"city2name":"武汉市"},
		{"city2name":"新洲区"}	]},
	{"city1name":"仙桃市","city2":[
		{"city2name":"仙桃市"}	]},
	{"city1name":"咸宁市","city2":[
		{"city2name":"赤壁市"},
		{"city2name":"崇阳县"},
		{"city2name":"嘉鱼县"},
		{"city2name":"通城县"},
		{"city2name":"通山县"},
		{"city2name":"咸安区"},
		{"city2name":"咸宁市"}	]},
	{"city1name":"襄樊市","city2":[
		{"city2name":"保康县"},
		{"city2name":"樊城区"},
		{"city2name":"谷城县"},
		{"city2name":"老河口市"},
		{"city2name":"南漳县"},
		{"city2name":"襄城区"},
		{"city2name":"襄樊市"},
		{"city2name":"襄阳区"},
		{"city2name":"宜城市"},
		{"city2name":"枣阳市"}	]},
	{"city1name":"孝感市","city2":[
		{"city2name":"安陆市"},
		{"city2name":"大悟县"},
		{"city2name":"汉川市"},
		{"city2name":"孝昌县"},
		{"city2name":"孝感市"},
		{"city2name":"孝南区"},
		{"city2name":"应城市"},
		{"city2name":"云梦县"}	]},
	{"city1name":"宜昌市","city2":[
		{"city2name":"长阳土家族自治县"},
		{"city2name":"当阳市"},
		{"city2name":"点军区"},
		{"city2name":"五峰土家族自治县"},
		{"city2name":"伍家岗区"},
		{"city2name":"西陵区"},
		{"city2name":"猇亭区"},
		{"city2name":"兴山县"},
		{"city2name":"夷陵区"},
		{"city2name":"宜昌市"},
		{"city2name":"宜都市"},
		{"city2name":"远安县"},
		{"city2name":"枝江市"},
		{"city2name":"秭归县"}	]} ]},
{"provname":"湖南","zone":"华中","city1":[
	{"city1name":"长沙市","city2":[
		{"city2name":"长沙市"},
		{"city2name":"长沙县"},
		{"city2name":"芙蓉区"},
		{"city2name":"开福区"},
		{"city2name":"浏阳市"},
		{"city2name":"宁乡县"},
		{"city2name":"天心区"},
		{"city2name":"望城县"},
		{"city2name":"雨花区"},
		{"city2name":"岳麓区"}	]},
	{"city1name":"常德市","city2":[
		{"city2name":"安乡县"},
		{"city2name":"常德市"},
		{"city2name":"鼎城区"},
		{"city2name":"汉寿县"},
		{"city2name":"津市市"},
		{"city2name":"澧县"},
		{"city2name":"临澧县"},
		{"city2name":"石门县"},
		{"city2name":"桃源县"},
		{"city2name":"武陵区"}	]},
	{"city1name":"郴州市","city2":[
		{"city2name":"安仁县"},
		{"city2name":"北湖区"},
		{"city2name":"郴州市"},
		{"city2name":"桂东县"},
		{"city2name":"桂阳县"},
		{"city2name":"嘉禾县"},
		{"city2name":"临武县"},
		{"city2name":"汝城县"},
		{"city2name":"苏仙区"},
		{"city2name":"宜章县"},
		{"city2name":"永兴县"},
		{"city2name":"资兴市"}	]},
	{"city1name":"衡阳市","city2":[
		{"city2name":"常宁市"},
		{"city2name":"衡东县"},
		{"city2name":"衡南县"},
		{"city2name":"衡山县"},
		{"city2name":"衡阳市"},
		{"city2name":"衡阳县"},
		{"city2name":"耒阳市"},
		{"city2name":"南岳区"},
		{"city2name":"祁东县"},
		{"city2name":"石鼓区"},
		{"city2name":"雁峰区"},
		{"city2name":"蒸湘区"},
		{"city2name":"珠晖区"}	]},
	{"city1name":"怀化市","city2":[
		{"city2name":"辰溪县"},
		{"city2name":"鹤城区"},
		{"city2name":"洪江市"},
		{"city2name":"怀化市"},
		{"city2name":"会同县"},
		{"city2name":"靖州苗族侗族自治县"},
		{"city2name":"麻阳苗族自治县"},
		{"city2name":"通道侗族自治县"},
		{"city2name":"新晃侗族自治县"},
		{"city2name":"溆浦县"},
		{"city2name":"沅陵县"},
		{"city2name":"芷江侗族自治县"},
		{"city2name":"中方县"}	]},
	{"city1name":"娄底市","city2":[
		{"city2name":"冷水江市"},
		{"city2name":"涟源市"},
		{"city2name":"娄底市"},
		{"city2name":"娄星区"},
		{"city2name":"双峰县"},
		{"city2name":"新化县"}	]},
	{"city1name":"邵阳市","city2":[
		{"city2name":"北塔区"},
		{"city2name":"城步苗族自治县"},
		{"city2name":"大祥区"},
		{"city2name":"洞口县"},
		{"city2name":"隆回县"},
		{"city2name":"邵东县"},
		{"city2name":"邵阳市"},
		{"city2name":"邵阳县"},
		{"city2name":"双清区"},
		{"city2name":"绥宁县"},
		{"city2name":"武冈市"},
		{"city2name":"新宁县"},
		{"city2name":"新邵县"}	]},
	{"city1name":"湘潭市","city2":[
		{"city2name":"韶山市"},
		{"city2name":"湘潭市"},
		{"city2name":"湘潭县"},
		{"city2name":"湘乡市"},
		{"city2name":"雨湖区"},
		{"city2name":"岳塘区"}	]},
	{"city1name":"湘西州","city2":[
		{"city2name":"保靖县"},
		{"city2name":"凤凰县"},
		{"city2name":"古丈县"},
		{"city2name":"花垣县"},
		{"city2name":"吉首市"},
		{"city2name":"龙山县"},
		{"city2name":"泸溪县"},
		{"city2name":"湘西州"},
		{"city2name":"永顺县"}	]},
	{"city1name":"益阳市","city2":[
		{"city2name":"安化县"},
		{"city2name":"赫山区"},
		{"city2name":"南县"},
		{"city2name":"桃江县"},
		{"city2name":"益阳市"},
		{"city2name":"沅江市"},
		{"city2name":"资阳区"}	]},
	{"city1name":"永州市","city2":[
		{"city2name":"道县"},
		{"city2name":"东安县"},
		{"city2name":"江华瑶族自治县"},
		{"city2name":"江永县"},
		{"city2name":"蓝山县"},
		{"city2name":"冷水滩区"},
		{"city2name":"宁远县"},
		{"city2name":"祁阳县"},
		{"city2name":"双牌县"},
		{"city2name":"新田县"},
		{"city2name":"永州市"},
		{"city2name":"芝山区"}	]},
	{"city1name":"岳阳市","city2":[
		{"city2name":"华容县"},
		{"city2name":"君山区"},
		{"city2name":"临湘市"},
		{"city2name":"汨罗市"},
		{"city2name":"平江县"},
		{"city2name":"湘阴县"},
		{"city2name":"岳阳楼区"},
		{"city2name":"岳阳市"},
		{"city2name":"岳阳县"},
		{"city2name":"云溪区"}	]},
	{"city1name":"张家界市","city2":[
		{"city2name":"慈利县"},
		{"city2name":"桑植县"},
		{"city2name":"武陵源区"},
		{"city2name":"永定区"},
		{"city2name":"张家界市"}	]},
	{"city1name":"株洲市","city2":[
		{"city2name":"茶陵县"},
		{"city2name":"荷塘区"},
		{"city2name":"醴陵市"},
		{"city2name":"芦淞区"},
		{"city2name":"石峰区"},
		{"city2name":"天元区"},
		{"city2name":"炎陵县"},
		{"city2name":"攸县"},
		{"city2name":"株洲市"},
		{"city2name":"株洲县"}	]} ]},
{"provname":"吉林","zone":"东北","city1":[
	{"city1name":"白城市","city2":[
		{"city2name":"白城市"},
		{"city2name":"大安市"},
		{"city2name":"洮北区"},
		{"city2name":"洮南市"},
		{"city2name":"通榆县"},
		{"city2name":"镇赉县"}	]},
	{"city1name":"白山市","city2":[
		{"city2name":"八道江区"},
		{"city2name":"白山市"},
		{"city2name":"长白朝鲜族自治县"},
		{"city2name":"抚松县"},
		{"city2name":"江源县"},
		{"city2name":"靖宇县"},
		{"city2name":"临江市"}	]},
	{"city1name":"长春市","city2":[
		{"city2name":"长春市"},
		{"city2name":"朝阳区"},
		{"city2name":"德惠市"},
		{"city2name":"二道区"},
		{"city2name":"九台市"},
		{"city2name":"宽城区"},
		{"city2name":"绿园区"},
		{"city2name":"南关区"},
		{"city2name":"农安县"},
		{"city2name":"双阳区"},
		{"city2name":"榆树市"}	]},
	{"city1name":"吉林市","city2":[
		{"city2name":"昌邑区"},
		{"city2name":"船营区"},
		{"city2name":"丰满区"},
		{"city2name":"桦甸市"},
		{"city2name":"吉林市"},
		{"city2name":"蛟河市"},
		{"city2name":"龙潭区"},
		{"city2name":"磐石市"},
		{"city2name":"舒兰市"},
		{"city2name":"永吉县"}	]},
	{"city1name":"辽源市","city2":[
		{"city2name":"东丰县"},
		{"city2name":"东辽县"},
		{"city2name":"辽源市"},
		{"city2name":"龙山区"},
		{"city2name":"西安区"}	]},
	{"city1name":"四平市","city2":[
		{"city2name":"公主岭市"},
		{"city2name":"梨树县"},
		{"city2name":"双辽市"},
		{"city2name":"四平市"},
		{"city2name":"铁东区"},
		{"city2name":"铁西区"},
		{"city2name":"伊通满族自治县"}	]},
	{"city1name":"松原市","city2":[
		{"city2name":"长岭县"},
		{"city2name":"扶余县"},
		{"city2name":"宁江区"},
		{"city2name":"前郭尔罗斯蒙古族自治县"},
		{"city2name":"乾安县"},
		{"city2name":"松原市"}	]},
	{"city1name":"通化市","city2":[
		{"city2name":"东昌区"},
		{"city2name":"二道江区"},
		{"city2name":"辉南县"},
		{"city2name":"集安市"},
		{"city2name":"柳河县"},
		{"city2name":"梅河口市"},
		{"city2name":"通化市"},
		{"city2name":"通化县"}	]},
	{"city1name":"延边州","city2":[
		{"city2name":"安图县"},
		{"city2name":"敦化市"},
		{"city2name":"和龙市"},
		{"city2name":"珲春市"},
		{"city2name":"龙井市"},
		{"city2name":"图们市"},
		{"city2name":"汪清县"},
		{"city2name":"延边州"},
		{"city2name":"延吉市"}	]} ]},
{"provname":"江苏","zone":"华东","city1":[
	{"city1name":"常州市","city2":[
		{"city2name":"常州市"},
		{"city2name":"金坛市"},
		{"city2name":"溧阳市"},
		{"city2name":"戚墅堰区"},
		{"city2name":"天宁区"},
		{"city2name":"武进区"},
		{"city2name":"新北区"},
		{"city2name":"钟楼区"}	]},
	{"city1name":"淮安市","city2":[
		{"city2name":"楚州区"},
		{"city2name":"洪泽县"},
		{"city2name":"淮安市"},
		{"city2name":"淮阴区"},
		{"city2name":"金湖县"},
		{"city2name":"涟水县"},
		{"city2name":"清河区"},
		{"city2name":"清浦区"},
		{"city2name":"盱眙县"}	]},
	{"city1name":"连云港市","city2":[
		{"city2name":"东海县"},
		{"city2name":"赣榆县"},
		{"city2name":"灌南县"},
		{"city2name":"灌云县"},
		{"city2name":"海州区"},
		{"city2name":"连云港市"},
		{"city2name":"连云区"},
		{"city2name":"新浦区"}	]},
	{"city1name":"南京市","city2":[
		{"city2name":"白下区"},
		{"city2name":"高淳县"},
		{"city2name":"鼓楼区"},
		{"city2name":"建邺区"},
		{"city2name":"江宁区"},
		{"city2name":"溧水县"},
		{"city2name":"六合区"},
		{"city2name":"南京市"},
		{"city2name":"浦口区"},
		{"city2name":"栖霞区"},
		{"city2name":"秦淮区"},
		{"city2name":"下关区"},
		{"city2name":"玄武区"},
		{"city2name":"雨花台区"}	]},
	{"city1name":"南通市","city2":[
		{"city2name":"崇川区"},
		{"city2name":"港闸区"},
		{"city2name":"海安县"},
		{"city2name":"海门市"},
		{"city2name":"南通市"},
		{"city2name":"启东市"},
		{"city2name":"如东县"},
		{"city2name":"如皋市"},
		{"city2name":"通州市"}	]},
	{"city1name":"盛泽","city2":[
		{"city2name":"盛泽"}	]},
	{"city1name":"苏州市","city2":[
		{"city2name":"沧浪区"},
		{"city2name":"常熟市"},
		{"city2name":"虎丘区"},
		{"city2name":"金阊区"},
		{"city2name":"昆山市"},
		{"city2name":"平江区"},
		{"city2name":"苏州市"},
		{"city2name":"太仓市"},
		{"city2name":"吴江市"},
		{"city2name":"吴中区"},
		{"city2name":"相城区"},
		{"city2name":"张家港市"}	]},
	{"city1name":"宿迁市","city2":[
		{"city2name":"沭阳县"},
		{"city2name":"泗洪县"},
		{"city2name":"泗阳县"},
		{"city2name":"宿城区"},
		{"city2name":"宿迁市"},
		{"city2name":"宿豫县"}	]},
	{"city1name":"泰州市","city2":[
		{"city2name":"高港区"},
		{"city2name":"海陵区"},
		{"city2name":"姜堰市"},
		{"city2name":"靖江市"},
		{"city2name":"泰兴市"},
		{"city2name":"泰州市"},
		{"city2name":"兴化市"}	]},
	{"city1name":"无锡市","city2":[
		{"city2name":"北塘区"},
		{"city2name":"滨湖区"},
		{"city2name":"崇安区"},
		{"city2name":"惠山区"},
		{"city2name":"江阴市"},
		{"city2name":"南长区"},
		{"city2name":"无锡市"},
		{"city2name":"锡山区"},
		{"city2name":"宜兴市"}	]},
	{"city1name":"徐州市","city2":[
		{"city2name":"丰县"},
		{"city2name":"贾汪区"},
		{"city2name":"九里区"},
		{"city2name":"沛县"},
		{"city2name":"邳州市"},
		{"city2name":"泉山区"},
		{"city2name":"睢宁县"},
		{"city2name":"铜山县"},
		{"city2name":"新沂市"},
		{"city2name":"徐州市"},
		{"city2name":"云龙区"}	]},
	{"city1name":"盐城市","city2":[
		{"city2name":"滨海县"},
		{"city2name":"城区"},
		{"city2name":"大丰市"},
		{"city2name":"东台市"},
		{"city2name":"阜宁县"},
		{"city2name":"建湖县"},
		{"city2name":"射阳县"},
		{"city2name":"响水县"},
		{"city2name":"盐城市"},
		{"city2name":"盐都县"}	]},
	{"city1name":"扬州市","city2":[
		{"city2name":"宝应县"},
		{"city2name":"高邮市"},
		{"city2name":"广陵区"},
		{"city2name":"邗江区"},
		{"city2name":"江都市"},
		{"city2name":"维扬区"},
		{"city2name":"扬州市"},
		{"city2name":"仪征市"}	]},
	{"city1name":"镇江市","city2":[
		{"city2name":"丹徒区"},
		{"city2name":"丹阳市"},
		{"city2name":"京口区"},
		{"city2name":"句容市"},
		{"city2name":"润州区"},
		{"city2name":"扬中市"},
		{"city2name":"镇江市"}	]} ]},
{"provname":"江西","zone":"华东","city1":[
	{"city1name":"抚州市","city2":[
		{"city2name":"崇仁县"},
		{"city2name":"东乡县"},
		{"city2name":"抚州市"},
		{"city2name":"广昌县"},
		{"city2name":"金溪县"},
		{"city2name":"乐安县"},
		{"city2name":"黎川县"},
		{"city2name":"临川区"},
		{"city2name":"南城县"},
		{"city2name":"南丰县"},
		{"city2name":"宜黄县"},
		{"city2name":"资溪县"}	]},
	{"city1name":"赣州市","city2":[
		{"city2name":"安远县"},
		{"city2name":"崇义县"},
		{"city2name":"大余县"},
		{"city2name":"定南县"},
		{"city2name":"赣县"},
		{"city2name":"赣州市"},
		{"city2name":"会昌县"},
		{"city2name":"龙南县"},
		{"city2name":"南康市"},
		{"city2name":"宁都县"},
		{"city2name":"全南县"},
		{"city2name":"瑞金市"},
		{"city2name":"上犹县"},
		{"city2name":"石城县"},
		{"city2name":"信丰县"},
		{"city2name":"兴国县"},
		{"city2name":"寻乌县"},
		{"city2name":"于都县"},
		{"city2name":"章贡区"}	]},
	{"city1name":"吉安市","city2":[
		{"city2name":"安福县"},
		{"city2name":"吉安市"},
		{"city2name":"吉安县"},
		{"city2name":"吉水县"},
		{"city2name":"吉州区"},
		{"city2name":"井冈山市"},
		{"city2name":"青原区"},
		{"city2name":"遂川县"},
		{"city2name":"泰和县"},
		{"city2name":"万安县"},
		{"city2name":"峡江县"},
		{"city2name":"新干县"},
		{"city2name":"永丰县"},
		{"city2name":"永新县"}	]},
	{"city1name":"景德镇市","city2":[
		{"city2name":"昌江区"},
		{"city2name":"浮梁县"},
		{"city2name":"景德镇市"},
		{"city2name":"乐平市"},
		{"city2name":"珠山区"}	]},
	{"city1name":"九江市","city2":[
		{"city2name":"德安县"},
		{"city2name":"都昌县"},
		{"city2name":"湖口县"},
		{"city2name":"九江市"},
		{"city2name":"九江县"},
		{"city2name":"庐山区"},
		{"city2name":"彭泽县"},
		{"city2name":"瑞昌市"},
		{"city2name":"武宁县"},
		{"city2name":"星子县"},
		{"city2name":"修水县"},
		{"city2name":"浔阳区"},
		{"city2name":"永修县"}	]},
	{"city1name":"南昌市","city2":[
		{"city2name":"安义县"},
		{"city2name":"东湖区"},
		{"city2name":"进贤县"},
		{"city2name":"南昌市"},
		{"city2name":"南昌县"},
		{"city2name":"青山湖区"},
		{"city2name":"青云谱区"},
		{"city2name":"湾里区"},
		{"city2name":"西湖区"},
		{"city2name":"新建县"}	]},
	{"city1name":"萍乡市","city2":[
		{"city2name":"安源区"},
		{"city2name":"莲花县"},
		{"city2name":"芦溪县"},
		{"city2name":"萍乡市"},
		{"city2name":"上栗县"},
		{"city2name":"湘东区"}	]},
	{"city1name":"上饶市","city2":[
		{"city2name":"波阳县"},
		{"city2name":"德兴市"},
		{"city2name":"广丰县"},
		{"city2name":"横峰县"},
		{"city2name":"铅山县"},
		{"city2name":"上饶市"},
		{"city2name":"上饶县"},
		{"city2name":"万年县"},
		{"city2name":"婺源县"},
		{"city2name":"信州区"},
		{"city2name":"弋阳县"},
		{"city2name":"余干县"},
		{"city2name":"玉山县"}	]},
	{"city1name":"新余市","city2":[
		{"city2name":"分宜县"},
		{"city2name":"新余市"},
		{"city2name":"渝水区"}	]},
	{"city1name":"宜春市","city2":[
		{"city2name":"丰城市"},
		{"city2name":"奉新县"},
		{"city2name":"高安市"},
		{"city2name":"靖安县"},
		{"city2name":"上高县"},
		{"city2name":"铜鼓县"},
		{"city2name":"万载县"},
		{"city2name":"宜春市"},
		{"city2name":"宜丰县"},
		{"city2name":"袁州区"},
		{"city2name":"樟树市"}	]},
	{"city1name":"鹰潭市","city2":[
		{"city2name":"贵溪市"},
		{"city2name":"鹰潭市"},
		{"city2name":"余江县"},
		{"city2name":"月湖区"}	]} ]},
{"provname":"辽宁","zone":"东北","city1":[
	{"city1name":"鞍山市","city2":[
		{"city2name":"鞍山市"},
		{"city2name":"海城市"},
		{"city2name":"立山区"},
		{"city2name":"千山区"},
		{"city2name":"台安县"},
		{"city2name":"铁东区"},
		{"city2name":"岫岩满族自治县"}	]},
	{"city1name":"本溪市","city2":[
		{"city2name":"本溪满族自治县"},
		{"city2name":"本溪市"},
		{"city2name":"桓仁满族自治县"},
		{"city2name":"明山区"},
		{"city2name":"南芬区"},
		{"city2name":"平山区"},
		{"city2name":"溪湖区"}	]},
	{"city1name":"朝阳市","city2":[
		{"city2name":"北票市"},
		{"city2name":"朝阳市"},
		{"city2name":"朝阳县"},
		{"city2name":"建平县"},
		{"city2name":"喀喇沁左翼蒙古族自治县"},
		{"city2name":"凌源市"},
		{"city2name":"龙城区"},
		{"city2name":"双塔区"}	]},
	{"city1name":"大连市","city2":[
		{"city2name":"长海县"},
		{"city2name":"大连市"},
		{"city2name":"甘井子区"},
		{"city2name":"金州区"},
		{"city2name":"旅顺口区"},
		{"city2name":"普兰店市"},
		{"city2name":"沙河口区"},
		{"city2name":"瓦房店市"},
		{"city2name":"西岗区"},
		{"city2name":"中山区"},
		{"city2name":"庄河市"}	]},
	{"city1name":"丹东市","city2":[
		{"city2name":"丹东市"},
		{"city2name":"东港市"},
		{"city2name":"凤城市"},
		{"city2name":"宽甸满族自治县"},
		{"city2name":"元宝区"},
		{"city2name":"振安区"},
		{"city2name":"振兴区"}	]},
	{"city1name":"抚顺市","city2":[
		{"city2name":"东洲区"},
		{"city2name":"抚顺市"},
		{"city2name":"抚顺县"},
		{"city2name":"清原满族自治县"},
		{"city2name":"顺城区"},
		{"city2name":"望花区"},
		{"city2name":"新宾满族自治县"},
		{"city2name":"新抚区"}	]},
	{"city1name":"阜新市","city2":[
		{"city2name":"阜新蒙古族自治县"},
		{"city2name":"阜新市"},
		{"city2name":"海州区"},
		{"city2name":"清河门区"},
		{"city2name":"太平区"},
		{"city2name":"细河区"},
		{"city2name":"新邱区"},
		{"city2name":"彰武县"}	]},
	{"city1name":"葫芦岛市","city2":[
		{"city2name":"葫芦岛市"},
		{"city2name":"建昌县"},
		{"city2name":"连山区"},
		{"city2name":"龙港区"},
		{"city2name":"南票区"},
		{"city2name":"绥中县"},
		{"city2name":"兴城市"}	]},
	{"city1name":"锦州市","city2":[
		{"city2name":"北宁市"},
		{"city2name":"古塔区"},
		{"city2name":"黑山县"},
		{"city2name":"锦州市"},
		{"city2name":"凌海市"},
		{"city2name":"凌河区"},
		{"city2name":"太和区"},
		{"city2name":"义县"}	]},
	{"city1name":"辽阳市","city2":[
		{"city2name":"白塔区"},
		{"city2name":"灯塔市"},
		{"city2name":"弓长岭区"},
		{"city2name":"宏伟区"},
		{"city2name":"辽阳市"},
		{"city2name":"辽阳县"},
		{"city2name":"太子河区"},
		{"city2name":"文圣区"}	]},
	{"city1name":"盘锦市","city2":[
		{"city2name":"大洼县"},
		{"city2name":"盘锦市"},
		{"city2name":"盘山县"},
		{"city2name":"双台子区"},
		{"city2name":"兴隆台区"}	]},
	{"city1name":"沈阳市","city2":[
		{"city2name":"大东区"},
		{"city2name":"东陵区"},
		{"city2name":"法库县"},
		{"city2name":"和平区"},
		{"city2name":"皇姑区"},
		{"city2name":"康平县"},
		{"city2name":"辽中县"},
		{"city2name":"沈河区"},
		{"city2name":"沈阳市"},
		{"city2name":"苏家屯区"},
		{"city2name":"铁西区"},
		{"city2name":"新城子区"},
		{"city2name":"新民市"},
		{"city2name":"于洪区"}	]},
	{"city1name":"铁岭市","city2":[
		{"city2name":"昌图县"},
		{"city2name":"调兵山市"},
		{"city2name":"开原市"},
		{"city2name":"清河区"},
		{"city2name":"铁岭市"},
		{"city2name":"铁岭县"},
		{"city2name":"西丰县"},
		{"city2name":"银州区"}	]},
	{"city1name":"营口市","city2":[
		{"city2name":"鲅鱼圈区"},
		{"city2name":"大石桥市"},
		{"city2name":"盖州市"},
		{"city2name":"老边区"},
		{"city2name":"西市区"},
		{"city2name":"营口市"},
		{"city2name":"站前区"}	]} ]},
{"provname":"内蒙","zone":"华北","city1":[
	{"city1name":"阿拉善盟","city2":[
		{"city2name":"阿拉善盟"},
		{"city2name":"阿拉善右旗"},
		{"city2name":"阿拉善左旗"},
		{"city2name":"额济纳旗"}	]},
	{"city1name":"巴彦淖尔盟","city2":[
		{"city2name":"巴彦淖尔盟"},
		{"city2name":"磴口县"},
		{"city2name":"杭锦后旗"},
		{"city2name":"临河市"},
		{"city2name":"乌拉特后旗"},
		{"city2name":"乌拉特前旗"},
		{"city2name":"乌拉特中旗"},
		{"city2name":"五原县"}	]},
	{"city1name":"包头市","city2":[
		{"city2name":"白云矿区"},
		{"city2name":"包头市"},
		{"city2name":"达尔罕茂明安联合旗"},
		{"city2name":"东河区"},
		{"city2name":"固阳县"},
		{"city2name":"九原区"},
		{"city2name":"昆都仑区"},
		{"city2name":"青山区"},
		{"city2name":"石拐区"},
		{"city2name":"土默特右旗"}	]},
	{"city1name":"赤峰市","city2":[
		{"city2name":"阿鲁科尔沁旗"},
		{"city2name":"敖汉旗"},
		{"city2name":"巴林右旗"},
		{"city2name":"巴林左旗"},
		{"city2name":"赤峰市"},
		{"city2name":"红山区"},
		{"city2name":"喀喇沁旗"},
		{"city2name":"克什克腾旗"},
		{"city2name":"林西县"},
		{"city2name":"宁城县"},
		{"city2name":"松山区"},
		{"city2name":"翁牛特旗"},
		{"city2name":"元宝山区"}	]},
	{"city1name":"鄂尔多斯市","city2":[
		{"city2name":"达拉特旗"},
		{"city2name":"东胜区"},
		{"city2name":"鄂尔多斯市"},
		{"city2name":"鄂托克旗"},
		{"city2name":"鄂托克前旗"},
		{"city2name":"杭锦旗"},
		{"city2name":"乌审旗"},
		{"city2name":"伊金霍洛旗"},
		{"city2name":"准格尔旗"}	]},
	{"city1name":"呼和浩特市","city2":[
		{"city2name":"和林格尔县"},
		{"city2name":"呼和浩特市"},
		{"city2name":"回民区"},
		{"city2name":"清水河县"},
		{"city2name":"赛罕区"},
		{"city2name":"土默特左旗"},
		{"city2name":"托克托县"},
		{"city2name":"武川县"},
		{"city2name":"新城区"},
		{"city2name":"玉泉区"}	]},
	{"city1name":"呼伦贝尔市","city2":[
		{"city2name":"阿荣旗"},
		{"city2name":"陈巴尔虎旗"},
		{"city2name":"额尔古纳市"},
		{"city2name":"鄂伦春自治旗"},
		{"city2name":"鄂温克族自治旗"},
		{"city2name":"根河市"},
		{"city2name":"海拉尔区"},
		{"city2name":"呼伦贝尔市"},
		{"city2name":"满洲里市"},
		{"city2name":"莫力达瓦达斡尔族自治旗"},
		{"city2name":"新巴尔虎右旗"},
		{"city2name":"新巴尔虎左旗"},
		{"city2name":"牙克石市"},
		{"city2name":"扎兰屯市"}	]},
	{"city1name":"通辽市","city2":[
		{"city2name":"霍林郭勒市"},
		{"city2name":"开鲁县"},
		{"city2name":"科尔沁区"},
		{"city2name":"科尔沁左翼后旗"},
		{"city2name":"科尔沁左翼中旗"},
		{"city2name":"库伦旗"},
		{"city2name":"奈曼旗"},
		{"city2name":"通辽市"},
		{"city2name":"扎鲁特旗"}	]},
	{"city1name":"乌海市","city2":[
		{"city2name":"海勃湾区"},
		{"city2name":"海南区"},
		{"city2name":"乌达区"},
		{"city2name":"乌海市"}	]},
	{"city1name":"乌兰察布盟","city2":[
		{"city2name":"察哈尔右翼后旗"},
		{"city2name":"察哈尔右翼中旗"},
		{"city2name":"丰镇市"},
		{"city2name":"化德县"},
		{"city2name":"集宁市"},
		{"city2name":"凉城县"},
		{"city2name":"商都县"},
		{"city2name":"四子王旗"},
		{"city2name":"乌兰察布盟"},
		{"city2name":"兴和县"},
		{"city2name":"卓资县"}	]},
	{"city1name":"锡林郭勒盟","city2":[
		{"city2name":"阿巴嘎旗"},
		{"city2name":"东乌珠穆沁旗"},
		{"city2name":"多伦县"},
		{"city2name":"二连浩特市"},
		{"city2name":"苏尼特右旗"},
		{"city2name":"苏尼特左旗"},
		{"city2name":"太仆寺旗"},
		{"city2name":"西乌珠穆沁旗"},
		{"city2name":"锡林郭勒盟"},
		{"city2name":"锡林浩特市"},
		{"city2name":"镶黄旗"},
		{"city2name":"正蓝旗"},
		{"city2name":"正镶白旗"}	]},
	{"city1name":"兴安盟","city2":[
		{"city2name":"阿尔山市"},
		{"city2name":"科尔沁右翼前旗"},
		{"city2name":"科尔沁右翼中旗"},
		{"city2name":"突泉县"},
		{"city2name":"乌兰浩特市"},
		{"city2name":"兴安盟"},
		{"city2name":"扎赉特旗"}	]} ]},
{"provname":"宁夏","zone":"西北","city1":[
	{"city1name":"固原市","city2":[
		{"city2name":"固原市"},
		{"city2name":"海原县"},
		{"city2name":"泾源县"},
		{"city2name":"隆德县"},
		{"city2name":"彭阳县"},
		{"city2name":"西吉县"},
		{"city2name":"原州区"}	]},
	{"city1name":"石嘴山市","city2":[
		{"city2name":"大武口区"},
		{"city2name":"惠农县"},
		{"city2name":"平罗县"},
		{"city2name":"石嘴山区"},
		{"city2name":"石嘴山市"},
		{"city2name":"陶乐县"}	]},
	{"city1name":"吴忠市","city2":[
		{"city2name":"利通区"},
		{"city2name":"灵武市"},
		{"city2name":"青铜峡市"},
		{"city2name":"同心县"},
		{"city2name":"吴忠市"},
		{"city2name":"盐池县"},
		{"city2name":"中宁县"},
		{"city2name":"中卫县"}	]},
	{"city1name":"银川市","city2":[
		{"city2name":"贺兰县"},
		{"city2name":"金凤区"},
		{"city2name":"西夏区"},
		{"city2name":"兴庆区"},
		{"city2name":"银川市"},
		{"city2name":"永宁县"}	]} ]},
{"provname":"青海","zone":"西北","city1":[
	{"city1name":"果洛州","city2":[
		{"city2name":"班玛县"},
		{"city2name":"达日县"},
		{"city2name":"甘德县"},
		{"city2name":"果洛州"},
		{"city2name":"久治县"},
		{"city2name":"玛多县"},
		{"city2name":"玛沁县"}	]},
	{"city1name":"海北州","city2":[
		{"city2name":"刚察县"},
		{"city2name":"海北州"},
		{"city2name":"海晏县"},
		{"city2name":"门源回族自治县"},
		{"city2name":"祁连县"}	]},
	{"city1name":"海东地区","city2":[
		{"city2name":"海东地区"},
		{"city2name":"互助土族自治县"},
		{"city2name":"化隆回族自治县"},
		{"city2name":"乐都县"},
		{"city2name":"民和回族土族自治县"},
		{"city2name":"平安县"},
		{"city2name":"循化撒拉族自治县"}	]},
	{"city1name":"海南州","city2":[
		{"city2name":"共和县"},
		{"city2name":"贵德县"},
		{"city2name":"贵南县"},
		{"city2name":"海南州"},
		{"city2name":"同德县"},
		{"city2name":"兴海县"}	]},
	{"city1name":"海西州","city2":[
		{"city2name":"德令哈市"},
		{"city2name":"都兰县"},
		{"city2name":"格尔木市"},
		{"city2name":"海西州"},
		{"city2name":"天峻县"},
		{"city2name":"乌兰县"}	]},
	{"city1name":"黄南州","city2":[
		{"city2name":"河南蒙古族自治县"},
		{"city2name":"黄南州"},
		{"city2name":"尖扎县"},
		{"city2name":"同仁县"},
		{"city2name":"泽库县"}	]},
	{"city1name":"西宁市","city2":[
		{"city2name":"城北区"},
		{"city2name":"城东区"},
		{"city2name":"城西区"},
		{"city2name":"城中区"},
		{"city2name":"大通回族土族自治县"},
		{"city2name":"湟源县"},
		{"city2name":"湟中县"},
		{"city2name":"西宁市"}	]},
	{"city1name":"玉树州","city2":[
		{"city2name":"称多县"},
		{"city2name":"囊谦县"},
		{"city2name":"曲麻莱县"},
		{"city2name":"玉树县"},
		{"city2name":"玉树州"},
		{"city2name":"杂多县"},
		{"city2name":"治多县"}	]} ]},
{"provname":"山东","zone":"华东","city1":[
	{"city1name":"滨州市","city2":[
		{"city2name":"滨城区"},
		{"city2name":"滨州市"},
		{"city2name":"博兴县"},
		{"city2name":"惠民县"},
		{"city2name":"无棣县"},
		{"city2name":"阳信县"},
		{"city2name":"沾化县"},
		{"city2name":"邹平县"}	]},
	{"city1name":"德州市","city2":[
		{"city2name":"德城区"},
		{"city2name":"德州市"},
		{"city2name":"乐陵市"},
		{"city2name":"临邑县"},
		{"city2name":"陵县"},
		{"city2name":"宁津县"},
		{"city2name":"平原县"},
		{"city2name":"齐河县"},
		{"city2name":"庆云县"},
		{"city2name":"武城县"},
		{"city2name":"夏津县"},
		{"city2name":"禹城市"}	]},
	{"city1name":"东营市","city2":[
		{"city2name":"东营区"},
		{"city2name":"东营市"},
		{"city2name":"广饶县"},
		{"city2name":"河口区"},
		{"city2name":"垦利县"},
		{"city2name":"利津县"}	]},
	{"city1name":"菏泽市","city2":[
		{"city2name":"曹县"},
		{"city2name":"成武县"},
		{"city2name":"单县"},
		{"city2name":"定陶县"},
		{"city2name":"东明县"},
		{"city2name":"菏泽市"},
		{"city2name":"巨野县"},
		{"city2name":"鄄城县"},
		{"city2name":"牡丹区"},
		{"city2name":"郓城县"}	]},
	{"city1name":"济南市","city2":[
		{"city2name":"长清区"},
		{"city2name":"槐荫区"},
		{"city2name":"济南市"},
		{"city2name":"济阳县"},
		{"city2name":"历城区"},
		{"city2name":"历下区"},
		{"city2name":"平阴县"},
		{"city2name":"商河县"},
		{"city2name":"市中区"},
		{"city2name":"天桥区"},
		{"city2name":"章丘市"}	]},
	{"city1name":"济宁市","city2":[
		{"city2name":"济宁市"},
		{"city2name":"嘉祥县"},
		{"city2name":"金乡县"},
		{"city2name":"梁山县"},
		{"city2name":"曲阜市"},
		{"city2name":"任城区"},
		{"city2name":"泗水县"},
		{"city2name":"微山县"},
		{"city2name":"汶上县"},
		{"city2name":"兖州市"},
		{"city2name":"鱼台县"},
		{"city2name":"邹城市"}	]},
	{"city1name":"莱芜市","city2":[
		{"city2name":"钢城区"},
		{"city2name":"莱城区"},
		{"city2name":"莱芜市"}	]},
	{"city1name":"聊城市","city2":[
		{"city2name":"茌平县"},
		{"city2name":"东阿县"},
		{"city2name":"东昌府区"},
		{"city2name":"高唐县"},
		{"city2name":"冠县"},
		{"city2name":"聊城市"},
		{"city2name":"临清市"},
		{"city2name":"莘县"},
		{"city2name":"阳谷县"}	]},
	{"city1name":"临沂市","city2":[
		{"city2name":"苍山县"},
		{"city2name":"费县"},
		{"city2name":"河东区"},
		{"city2name":"莒南县"},
		{"city2name":"兰山区"},
		{"city2name":"临沭县"},
		{"city2name":"临沂市"},
		{"city2name":"罗庄区"},
		{"city2name":"蒙阴县"},
		{"city2name":"平邑县"},
		{"city2name":"郯城县"},
		{"city2name":"沂南县"},
		{"city2name":"沂水县"}	]},
	{"city1name":"青岛市","city2":[
		{"city2name":"城阳区"},
		{"city2name":"黄岛区"},
		{"city2name":"即墨市"},
		{"city2name":"胶南市"},
		{"city2name":"胶州市"},
		{"city2name":"莱西市"},
		{"city2name":"崂山区"},
		{"city2name":"李沧区"},
		{"city2name":"平度市"},
		{"city2name":"青岛市"},
		{"city2name":"市北区"},
		{"city2name":"市南区"},
		{"city2name":"四方区"}	]},
	{"city1name":"日照市","city2":[
		{"city2name":"东港区"},
		{"city2name":"莒县"},
		{"city2name":"日照市"},
		{"city2name":"五莲县"}	]},
	{"city1name":"泰安市","city2":[
		{"city2name":"岱岳区"},
		{"city2name":"东平县"},
		{"city2name":"肥城市"},
		{"city2name":"宁阳县"},
		{"city2name":"泰安市"},
		{"city2name":"泰山区"},
		{"city2name":"新泰市"}	]},
	{"city1name":"威海市","city2":[
		{"city2name":"环翠区"},
		{"city2name":"荣成市"},
		{"city2name":"乳山市"},
		{"city2name":"威海市"},
		{"city2name":"文登市"}	]},
	{"city1name":"潍坊市","city2":[
		{"city2name":"安丘市"},
		{"city2name":"昌乐县"},
		{"city2name":"昌邑市"},
		{"city2name":"坊子区"},
		{"city2name":"高密市"},
		{"city2name":"寒亭区"},
		{"city2name":"奎文区"},
		{"city2name":"临朐县"},
		{"city2name":"青州市"},
		{"city2name":"寿光市"},
		{"city2name":"潍城区"},
		{"city2name":"潍坊市"},
		{"city2name":"诸城市"}	]},
	{"city1name":"烟台市","city2":[
		{"city2name":"长岛县"},
		{"city2name":"福山区"},
		{"city2name":"海阳市"},
		{"city2name":"莱山区"},
		{"city2name":"莱阳市"},
		{"city2name":"莱州市"},
		{"city2name":"龙口市"},
		{"city2name":"牟平区"},
		{"city2name":"蓬莱市"},
		{"city2name":"栖霞市"},
		{"city2name":"烟台市"},
		{"city2name":"招远市"},
		{"city2name":"芝罘区"}	]},
	{"city1name":"枣庄市","city2":[
		{"city2name":"山亭区"},
		{"city2name":"台儿庄区"},
		{"city2name":"滕州市"},
		{"city2name":"薛城区"},
		{"city2name":"峄城区"},
		{"city2name":"枣庄市"}	]},
	{"city1name":"淄博市","city2":[
		{"city2name":"博山区"},
		{"city2name":"高青县"},
		{"city2name":"桓台县"},
		{"city2name":"临淄区"},
		{"city2name":"沂源县"},
		{"city2name":"张店区"},
		{"city2name":"周村区"},
		{"city2name":"淄博市"},
		{"city2name":"淄川区"}	]} ]},
{"provname":"山西","zone":"华北","city1":[
	{"city1name":"长治市","city2":[
		{"city2name":"长治市"},
		{"city2name":"长治县"},
		{"city2name":"长子县"},
		{"city2name":"壶关县"},
		{"city2name":"黎城县"},
		{"city2name":"潞城市"},
		{"city2name":"平顺县"},
		{"city2name":"沁县"},
		{"city2name":"沁源县"},
		{"city2name":"屯留县"},
		{"city2name":"武乡县"},
		{"city2name":"襄垣县"}	]},
	{"city1name":"大同市","city2":[
		{"city2name":"城区"},
		{"city2name":"大同市"},
		{"city2name":"大同县"},
		{"city2name":"广灵县"},
		{"city2name":"浑源县"},
		{"city2name":"矿区"},
		{"city2name":"灵丘县"},
		{"city2name":"南郊区"},
		{"city2name":"天镇县"},
		{"city2name":"新荣区"},
		{"city2name":"阳高县"},
		{"city2name":"左云县"}	]},
	{"city1name":"晋城市","city2":[
		{"city2name":"高平市"},
		{"city2name":"晋城市"},
		{"city2name":"陵川县"},
		{"city2name":"沁水县"},
		{"city2name":"阳城县"},
		{"city2name":"泽州县"}	]},
	{"city1name":"晋中市","city2":[
		{"city2name":"和顺县"},
		{"city2name":"介休市"},
		{"city2name":"晋中市"},
		{"city2name":"灵石县"},
		{"city2name":"平遥县"},
		{"city2name":"祁县"},
		{"city2name":"寿阳县"},
		{"city2name":"太谷县"},
		{"city2name":"昔阳县"},
		{"city2name":"榆次区"},
		{"city2name":"榆社县"},
		{"city2name":"左权县"}	]},
	{"city1name":"临汾市","city2":[
		{"city2name":"安泽县"},
		{"city2name":"大宁县"},
		{"city2name":"汾西县"},
		{"city2name":"浮山县"},
		{"city2name":"古县"},
		{"city2name":"洪洞县"},
		{"city2name":"侯马市"},
		{"city2name":"霍州市"},
		{"city2name":"吉县"},
		{"city2name":"临汾市"},
		{"city2name":"蒲县"},
		{"city2name":"曲沃县"},
		{"city2name":"隰县"},
		{"city2name":"乡宁县"},
		{"city2name":"襄汾县"},
		{"city2name":"尧都区"},
		{"city2name":"翼城县"},
		{"city2name":"永和县"}	]},
	{"city1name":"吕梁地区","city2":[
		{"city2name":"方山县"},
		{"city2name":"汾阳市"},
		{"city2name":"交城县"},
		{"city2name":"交口县"},
		{"city2name":"岚县"},
		{"city2name":"离石市"},
		{"city2name":"临县"},
		{"city2name":"柳林县"},
		{"city2name":"吕梁地区"},
		{"city2name":"石楼县"},
		{"city2name":"文水县"},
		{"city2name":"孝义市"},
		{"city2name":"兴县"},
		{"city2name":"中阳县"}	]},
	{"city1name":"朔州市","city2":[
		{"city2name":"怀仁县"},
		{"city2name":"平鲁区"},
		{"city2name":"山阴县"},
		{"city2name":"朔城区"},
		{"city2name":"朔州市"},
		{"city2name":"应县"},
		{"city2name":"右玉县"}	]},
	{"city1name":"太原市","city2":[
		{"city2name":"古交市"},
		{"city2name":"尖草坪区"},
		{"city2name":"晋源区"},
		{"city2name":"娄烦县"},
		{"city2name":"清徐县"},
		{"city2name":"太原市"},
		{"city2name":"万柏林区"},
		{"city2name":"小店区"},
		{"city2name":"杏花岭区"},
		{"city2name":"阳曲县"},
		{"city2name":"迎泽区"}	]},
	{"city1name":"忻州市","city2":[
		{"city2name":"保德县"},
		{"city2name":"代县"},
		{"city2name":"定襄县"},
		{"city2name":"繁峙县"},
		{"city2name":"河曲县"},
		{"city2name":"静乐县"},
		{"city2name":"岢岚县"},
		{"city2name":"宁武县"},
		{"city2name":"偏关县"},
		{"city2name":"神池县"},
		{"city2name":"五台县"},
		{"city2name":"五寨县"},
		{"city2name":"忻府区"},
		{"city2name":"忻州市"},
		{"city2name":"原平市"}	]},
	{"city1name":"阳泉市","city2":[
		{"city2name":"郊区"},
		{"city2name":"平定县"},
		{"city2name":"阳泉市"},
		{"city2name":"盂县"}	]},
	{"city1name":"运城市","city2":[
		{"city2name":"河津市"},
		{"city2name":"稷山县"},
		{"city2name":"绛县"},
		{"city2name":"临猗县"},
		{"city2name":"平陆县"},
		{"city2name":"芮城县"},
		{"city2name":"万荣县"},
		{"city2name":"闻喜县"},
		{"city2name":"夏县"},
		{"city2name":"新绛县"},
		{"city2name":"盐湖区"},
		{"city2name":"永济市"},
		{"city2name":"垣曲县"},
		{"city2name":"运城市"}	]} ]},
{"provname":"陕西","zone":"西北","city1":[
	{"city1name":"安康市","city2":[
		{"city2name":"安康市"},
		{"city2name":"白河县"},
		{"city2name":"汉滨区"},
		{"city2name":"汉阴县"},
		{"city2name":"岚皋县"},
		{"city2name":"宁陕县"},
		{"city2name":"平利县"},
		{"city2name":"石泉县"},
		{"city2name":"旬阳县"},
		{"city2name":"镇坪县"},
		{"city2name":"紫阳县"}	]},
	{"city1name":"宝鸡市","city2":[
		{"city2name":"宝鸡市"},
		{"city2name":"宝鸡县"},
		{"city2name":"凤县"},
		{"city2name":"凤翔县"},
		{"city2name":"扶风县"},
		{"city2name":"金台区"},
		{"city2name":"麟游县"},
		{"city2name":"陇县"},
		{"city2name":"眉县"},
		{"city2name":"岐山县"},
		{"city2name":"千阳县"},
		{"city2name":"太白县"},
		{"city2name":"渭滨区"}	]},
	{"city1name":"汉中市","city2":[
		{"city2name":"城固县"},
		{"city2name":"佛坪县"},
		{"city2name":"汉台区"},
		{"city2name":"汉中市"},
		{"city2name":"留坝县"},
		{"city2name":"略阳县"},
		{"city2name":"勉县"},
		{"city2name":"南郑县"},
		{"city2name":"宁强县"},
		{"city2name":"西乡县"},
		{"city2name":"洋县"},
		{"city2name":"镇巴县"}	]},
	{"city1name":"商洛市","city2":[
		{"city2name":"丹凤县"},
		{"city2name":"洛南县"},
		{"city2name":"山阳县"},
		{"city2name":"商洛市"},
		{"city2name":"商南县"},
		{"city2name":"商州区"},
		{"city2name":"镇安县"},
		{"city2name":"柞水县"}	]},
	{"city1name":"铜川市","city2":[
		{"city2name":"铜川市"},
		{"city2name":"王益区"},
		{"city2name":"耀州区"},
		{"city2name":"宜君县"},
		{"city2name":"印台区"}	]},
	{"city1name":"渭南市","city2":[
		{"city2name":"白水县"},
		{"city2name":"澄城县"},
		{"city2name":"大荔县"},
		{"city2name":"富平县"},
		{"city2name":"韩城市"},
		{"city2name":"合阳县"},
		{"city2name":"华县"},
		{"city2name":"华阴市"},
		{"city2name":"临渭区"},
		{"city2name":"蒲城县"},
		{"city2name":"潼关县"},
		{"city2name":"渭南市"}	]},
	{"city1name":"西安市","city2":[
		{"city2name":"灞桥区"},
		{"city2name":"碑林区"},
		{"city2name":"长安区"},
		{"city2name":"高陵县"},
		{"city2name":"户县"},
		{"city2name":"蓝田县"},
		{"city2name":"莲湖区"},
		{"city2name":"临潼区"},
		{"city2name":"未央区"},
		{"city2name":"西安市"},
		{"city2name":"新城区"},
		{"city2name":"阎良区"},
		{"city2name":"雁塔区"},
		{"city2name":"周至县"}	]},
	{"city1name":"咸阳市","city2":[
		{"city2name":"彬县"},
		{"city2name":"长武县"},
		{"city2name":"淳化县"},
		{"city2name":"泾阳县"},
		{"city2name":"礼泉县"},
		{"city2name":"乾县"},
		{"city2name":"秦都区"},
		{"city2name":"三原县"},
		{"city2name":"渭城区"},
		{"city2name":"武功县"},
		{"city2name":"咸阳市"},
		{"city2name":"兴平市"},
		{"city2name":"旬邑县"},
		{"city2name":"杨凌区"},
		{"city2name":"永寿县"}	]},
	{"city1name":"延安市","city2":[
		{"city2name":"安塞县"},
		{"city2name":"宝塔区"},
		{"city2name":"富县"},
		{"city2name":"甘泉县"},
		{"city2name":"黄陵县"},
		{"city2name":"黄龙县"},
		{"city2name":"洛川县"},
		{"city2name":"吴旗县"},
		{"city2name":"延安市"},
		{"city2name":"延长县"},
		{"city2name":"延川县"},
		{"city2name":"宜川县"},
		{"city2name":"志丹县"},
		{"city2name":"子长县"}	]},
	{"city1name":"榆林市","city2":[
		{"city2name":"定边县"},
		{"city2name":"府谷县"},
		{"city2name":"横山县"},
		{"city2name":"佳县"},
		{"city2name":"靖边县"},
		{"city2name":"米脂县"},
		{"city2name":"清涧县"},
		{"city2name":"神木县"},
		{"city2name":"绥德县"},
		{"city2name":"吴堡县"},
		{"city2name":"榆林市"},
		{"city2name":"榆阳区"},
		{"city2name":"子洲县"}	]} ]},
{"provname":"上海","zone":"华东","city1":[
	{"city1name":"上海","city2":[
		{"city2name":"宝山区"},
		{"city2name":"长宁区"},
		{"city2name":"崇明县"},
		{"city2name":"奉贤区"},
		{"city2name":"虹口区"},
		{"city2name":"黄浦区"},
		{"city2name":"嘉定区"},
		{"city2name":"金山区"},
		{"city2name":"静安区"},
		{"city2name":"卢湾区"},
		{"city2name":"闵行区"},
		{"city2name":"南汇区"},
		{"city2name":"浦东新区"},
		{"city2name":"普陀区"},
		{"city2name":"青浦区"},
		{"city2name":"上海"},
		{"city2name":"松江区"},
		{"city2name":"徐汇区"},
		{"city2name":"杨浦区"},
		{"city2name":"闸北区"}	]} ]},
{"provname":"四川","zone":"西南","city1":[
	{"city1name":"阿坝州","city2":[
		{"city2name":"阿坝县"},
		{"city2name":"阿坝州"},
		{"city2name":"黑水县"},
		{"city2name":"红原县"},
		{"city2name":"金川县"},
		{"city2name":"九寨沟县"},
		{"city2name":"理县"},
		{"city2name":"马尔康县"},
		{"city2name":"茂县"},
		{"city2name":"壤塘县"},
		{"city2name":"若尔盖县"},
		{"city2name":"松潘县"},
		{"city2name":"汶川县"},
		{"city2name":"小金县"}	]},
	{"city1name":"巴中市","city2":[
		{"city2name":"巴中市"},
		{"city2name":"巴州区"},
		{"city2name":"南江县"},
		{"city2name":"平昌县"},
		{"city2name":"通江县"}	]},
	{"city1name":"成都市","city2":[
		{"city2name":"成都市"},
		{"city2name":"成华区"},
		{"city2name":"崇州市"},
		{"city2name":"大邑县"},
		{"city2name":"都江堰市"},
		{"city2name":"金牛区"},
		{"city2name":"金堂县"},
		{"city2name":"锦江区"},
		{"city2name":"龙泉驿区"},
		{"city2name":"彭州市"},
		{"city2name":"郫县"},
		{"city2name":"蒲江县"},
		{"city2name":"青白江区"},
		{"city2name":"青羊区"},
		{"city2name":"邛崃市"},
		{"city2name":"双流县"},
		{"city2name":"温江区"},
		{"city2name":"武侯区"},
		{"city2name":"新都区"},
		{"city2name":"新津县"}	]},
	{"city1name":"达州市","city2":[
		{"city2name":"达县"},
		{"city2name":"达州市"},
		{"city2name":"大竹县"},
		{"city2name":"开江县"},
		{"city2name":"渠县"},
		{"city2name":"通川区"},
		{"city2name":"万源市"},
		{"city2name":"宣汉县"}	]},
	{"city1name":"德阳市","city2":[
		{"city2name":"德阳市"},
		{"city2name":"广汉市"},
		{"city2name":"旌阳区"},
		{"city2name":"罗江县"},
		{"city2name":"绵竹市"},
		{"city2name":"什邡市"},
		{"city2name":"中江县"}	]},
	{"city1name":"甘孜州","city2":[
		{"city2name":"巴塘县"},
		{"city2name":"白玉县"},
		{"city2name":"丹巴县"},
		{"city2name":"道孚县"},
		{"city2name":"稻城县"},
		{"city2name":"得荣县"},
		{"city2name":"德格县"},
		{"city2name":"甘孜县"},
		{"city2name":"甘孜州"},
		{"city2name":"九龙县"},
		{"city2name":"康定县"},
		{"city2name":"理塘县"},
		{"city2name":"泸定县"},
		{"city2name":"炉霍县"},
		{"city2name":"色达县"},
		{"city2name":"石渠县"},
		{"city2name":"乡城县"},
		{"city2name":"新龙县"},
		{"city2name":"雅江县"}	]},
	{"city1name":"广安市","city2":[
		{"city2name":"广安区"},
		{"city2name":"广安市"},
		{"city2name":"华蓥市"},
		{"city2name":"邻水县"},
		{"city2name":"武胜县"},
		{"city2name":"岳池县"}	]},
	{"city1name":"广元市","city2":[
		{"city2name":"苍溪县"},
		{"city2name":"朝天区"},
		{"city2name":"广元市"},
		{"city2name":"剑阁县"},
		{"city2name":"青川县"},
		{"city2name":"市中区"},
		{"city2name":"旺苍县"},
		{"city2name":"元坝区"}	]},
	{"city1name":"乐山市","city2":[
		{"city2name":"峨边彝族自治县"},
		{"city2name":"峨眉山市"},
		{"city2name":"夹江县"},
		{"city2name":"犍为县"},
		{"city2name":"金口河区"},
		{"city2name":"井研县"},
		{"city2name":"乐山市"},
		{"city2name":"马边彝族自治县"},
		{"city2name":"沐川县"},
		{"city2name":"沙湾区"},
		{"city2name":"五通桥区"}	]},
	{"city1name":"凉山州","city2":[
		{"city2name":"布拖县"},
		{"city2name":"德昌县"},
		{"city2name":"甘洛县"},
		{"city2name":"会东县"},
		{"city2name":"会理县"},
		{"city2name":"金阳县"},
		{"city2name":"雷波县"},
		{"city2name":"凉山州"},
		{"city2name":"美姑县"},
		{"city2name":"冕宁县"},
		{"city2name":"木里藏族自治县"},
		{"city2name":"宁南县"},
		{"city2name":"普格县"},
		{"city2name":"西昌市"},
		{"city2name":"喜德县"},
		{"city2name":"盐源县"},
		{"city2name":"越西县"},
		{"city2name":"昭觉县"}	]},
	{"city1name":"泸州市","city2":[
		{"city2name":"古蔺县"},
		{"city2name":"合江县"},
		{"city2name":"江阳区"},
		{"city2name":"龙马潭区"},
		{"city2name":"泸县"},
		{"city2name":"泸州市"},
		{"city2name":"纳溪区"},
		{"city2name":"叙永县"}	]},
	{"city1name":"眉山市","city2":[
		{"city2name":"丹棱县"},
		{"city2name":"东坡区"},
		{"city2name":"洪雅县"},
		{"city2name":"眉山市"},
		{"city2name":"彭山县"},
		{"city2name":"青神县"},
		{"city2name":"仁寿县"}	]},
	{"city1name":"绵阳市","city2":[
		{"city2name":"安县"},
		{"city2name":"北川县"},
		{"city2name":"涪城区"},
		{"city2name":"江油市"},
		{"city2name":"绵阳市"},
		{"city2name":"平武县"},
		{"city2name":"三台县"},
		{"city2name":"盐亭县"},
		{"city2name":"游仙区"},
		{"city2name":"梓潼县"}	]},
	{"city1name":"内江市","city2":[
		{"city2name":"东兴区"},
		{"city2name":"隆昌县"},
		{"city2name":"内江市"},
		{"city2name":"威远县"},
		{"city2name":"资中县"}	]},
	{"city1name":"南充市","city2":[
		{"city2name":"高坪区"},
		{"city2name":"嘉陵区"},
		{"city2name":"阆中市"},
		{"city2name":"南部县"},
		{"city2name":"南充市"},
		{"city2name":"蓬安县"},
		{"city2name":"顺庆区"},
		{"city2name":"西充县"},
		{"city2name":"仪陇县"},
		{"city2name":"营山县"}	]},
	{"city1name":"攀枝花市","city2":[
		{"city2name":"东区"},
		{"city2name":"米易县"},
		{"city2name":"攀枝花市"},
		{"city2name":"仁和区"},
		{"city2name":"西区"},
		{"city2name":"盐边县"}	]},
	{"city1name":"遂宁市","city2":[
		{"city2name":"大英县"},
		{"city2name":"蓬溪县"},
		{"city2name":"射洪县"},
		{"city2name":"遂宁市"}	]},
	{"city1name":"雅安市","city2":[
		{"city2name":"宝兴县"},
		{"city2name":"汉源县"},
		{"city2name":"芦山县"},
		{"city2name":"名山县"},
		{"city2name":"石棉县"},
		{"city2name":"天全县"},
		{"city2name":"雅安市"},
		{"city2name":"荥经县"},
		{"city2name":"雨城区"}	]},
	{"city1name":"宜宾市","city2":[
		{"city2name":"长宁县"},
		{"city2name":"翠屏区"},
		{"city2name":"高县"},
		{"city2name":"珙县"},
		{"city2name":"江安县"},
		{"city2name":"筠连县"},
		{"city2name":"南溪县"},
		{"city2name":"屏山县"},
		{"city2name":"兴文县"},
		{"city2name":"宜宾市"},
		{"city2name":"宜宾县"}	]},
	{"city1name":"资阳市","city2":[
		{"city2name":"安岳县"},
		{"city2name":"简阳市"},
		{"city2name":"乐至县"},
		{"city2name":"雁江区"},
		{"city2name":"资阳市"}	]},
	{"city1name":"自贡市","city2":[
		{"city2name":"大安区"},
		{"city2name":"富顺县"},
		{"city2name":"贡井区"},
		{"city2name":"荣县"},
		{"city2name":"沿滩区"},
		{"city2name":"自贡市"},
		{"city2name":"自流井区"}	]} ]},
{"provname":"天津","zone":"华北","city1":[
	{"city1name":"天津","city2":[
		{"city2name":"宝坻区"},
		{"city2name":"北辰区"},
		{"city2name":"大港区"},
		{"city2name":"东丽区"},
		{"city2name":"汉沽区"},
		{"city2name":"和平区"},
		{"city2name":"河北区"},
		{"city2name":"河东区"},
		{"city2name":"河西区"},
		{"city2name":"红桥区"},
		{"city2name":"蓟县"},
		{"city2name":"津南区"},
		{"city2name":"静海县"},
		{"city2name":"南开区"},
		{"city2name":"宁河县"},
		{"city2name":"塘沽区"},
		{"city2name":"天津"},
		{"city2name":"武清区"},
		{"city2name":"西青区"}	]} ]},
{"provname":"西藏","zone":"西南","city1":[
	{"city1name":"阿里地区","city2":[
		{"city2name":"阿里地区"},
		{"city2name":"措勤县"},
		{"city2name":"噶尔县"},
		{"city2name":"改则县"},
		{"city2name":"革吉县"},
		{"city2name":"普兰县"},
		{"city2name":"日土县"},
		{"city2name":"札达县"}	]},
	{"city1name":"昌都地区","city2":[
		{"city2name":"八宿县"},
		{"city2name":"边坝县"},
		{"city2name":"察雅县"},
		{"city2name":"昌都地区"},
		{"city2name":"昌都县"},
		{"city2name":"丁青县"},
		{"city2name":"贡觉县"},
		{"city2name":"江达县"},
		{"city2name":"类乌齐县"},
		{"city2name":"洛隆县"},
		{"city2name":"芒康县"},
		{"city2name":"左贡县"}	]},
	{"city1name":"拉萨市","city2":[
		{"city2name":"城关区"},
		{"city2name":"达孜县"},
		{"city2name":"当雄县"},
		{"city2name":"堆龙德庆县"},
		{"city2name":"拉萨市"},
		{"city2name":"林周县"},
		{"city2name":"墨竹工卡县"},
		{"city2name":"尼木县"},
		{"city2name":"曲水县"}	]},
	{"city1name":"林芝地区","city2":[
		{"city2name":"波密县"},
		{"city2name":"察隅县"},
		{"city2name":"工布江达县"},
		{"city2name":"朗县"},
		{"city2name":"林芝地区"},
		{"city2name":"林芝县"},
		{"city2name":"米林县"},
		{"city2name":"墨脱县"}	]},
	{"city1name":"那曲地区","city2":[
		{"city2name":"安多县"},
		{"city2name":"巴青县"},
		{"city2name":"班戈县"},
		{"city2name":"比如县"},
		{"city2name":"嘉黎县"},
		{"city2name":"那曲地区"},
		{"city2name":"那曲县"},
		{"city2name":"尼玛县"},
		{"city2name":"聂荣县"},
		{"city2name":"申扎县"},
		{"city2name":"索县"}	]},
	{"city1name":"日喀则地区","city2":[
		{"city2name":"昂仁县"},
		{"city2name":"白朗县"},
		{"city2name":"定结县"},
		{"city2name":"定日县"},
		{"city2name":"岗巴县"},
		{"city2name":"吉隆县"},
		{"city2name":"江孜县"},
		{"city2name":"康马县"},
		{"city2name":"拉孜县"},
		{"city2name":"南木林县"},
		{"city2name":"聂拉木县"},
		{"city2name":"仁布县"},
		{"city2name":"日喀则地区"},
		{"city2name":"日喀则市"},
		{"city2name":"萨嘎县"},
		{"city2name":"萨迦县"},
		{"city2name":"谢通门县"},
		{"city2name":"亚东县"},
		{"city2name":"仲巴县"}	]},
	{"city1name":"山南地区","city2":[
		{"city2name":"措美县"},
		{"city2name":"错那县"},
		{"city2name":"贡嘎县"},
		{"city2name":"加查县"},
		{"city2name":"浪卡子县"},
		{"city2name":"隆子县"},
		{"city2name":"洛扎县"},
		{"city2name":"乃东县"},
		{"city2name":"琼结县"},
		{"city2name":"曲松县"},
		{"city2name":"桑日县"},
		{"city2name":"山南地区"},
		{"city2name":"扎囊县"}	]} ]},
{"provname":"新疆","zone":"西北","city1":[
	{"city1name":"阿克苏地区","city2":[
		{"city2name":"阿克苏地区"},
		{"city2name":"阿克苏市"},
		{"city2name":"阿瓦提县"},
		{"city2name":"拜城县"},
		{"city2name":"柯坪县"},
		{"city2name":"库车县"},
		{"city2name":"沙雅县"},
		{"city2name":"温宿县"},
		{"city2name":"乌什县"},
		{"city2name":"新和县"}	]},
	{"city1name":"阿拉尔市","city2":[
		{"city2name":"阿拉尔市"}	]},
	{"city1name":"阿勒泰地区","city2":[
		{"city2name":"阿勒泰地区"},
		{"city2name":"阿勒泰市"},
		{"city2name":"布尔津县"},
		{"city2name":"福海县"},
		{"city2name":"富蕴县"},
		{"city2name":"哈巴河县"},
		{"city2name":"吉木乃县"},
		{"city2name":"青河县"}	]},
	{"city1name":"巴音郭楞州","city2":[
		{"city2name":"巴音郭楞州"},
		{"city2name":"博湖县"},
		{"city2name":"和静县"},
		{"city2name":"和硕县"},
		{"city2name":"库尔勒市"},
		{"city2name":"轮台县"},
		{"city2name":"且末县"},
		{"city2name":"若羌县"},
		{"city2name":"尉犁县"},
		{"city2name":"焉耆回族自治县"}	]},
	{"city1name":"博尔塔拉州","city2":[
		{"city2name":"博尔塔拉州"},
		{"city2name":"博乐市"},
		{"city2name":"精河县"},
		{"city2name":"温泉县"}	]},
	{"city1name":"昌吉州","city2":[
		{"city2name":"昌吉市"},
		{"city2name":"昌吉州"},
		{"city2name":"阜康市"},
		{"city2name":"呼图壁县"},
		{"city2name":"吉木萨尔县"},
		{"city2name":"玛纳斯县"},
		{"city2name":"米泉市"},
		{"city2name":"木垒哈萨克自治县"},
		{"city2name":"奇台县"}	]},
	{"city1name":"哈密地区","city2":[
		{"city2name":"巴里坤哈萨克自治县"},
		{"city2name":"哈密地区"},
		{"city2name":"哈密市"},
		{"city2name":"伊吾县"}	]},
	{"city1name":"和田地区","city2":[
		{"city2name":"策勒县"},
		{"city2name":"和田地区"},
		{"city2name":"和田市"},
		{"city2name":"和田县"},
		{"city2name":"洛浦县"},
		{"city2name":"民丰县"},
		{"city2name":"墨玉县"},
		{"city2name":"皮山县"},
		{"city2name":"于田县"}	]},
	{"city1name":"喀什地区","city2":[
		{"city2name":"巴楚县"},
		{"city2name":"伽师县"},
		{"city2name":"喀什地区"},
		{"city2name":"喀什市"},
		{"city2name":"麦盖提县"},
		{"city2name":"莎车县"},
		{"city2name":"疏附县"},
		{"city2name":"疏勒县"},
		{"city2name":"塔什库尔干塔吉克自治县"},
		{"city2name":"叶城县"},
		{"city2name":"英吉沙县"},
		{"city2name":"岳普湖县"},
		{"city2name":"泽普县"}	]},
	{"city1name":"克拉玛依市","city2":[
		{"city2name":"白碱滩区"},
		{"city2name":"独山子区"},
		{"city2name":"克拉玛依区"},
		{"city2name":"克拉玛依市"},
		{"city2name":"乌尔禾区"}	]},
	{"city1name":"克孜勒苏州","city2":[
		{"city2name":"阿合奇县"},
		{"city2name":"阿克陶县"},
		{"city2name":"阿图什市"},
		{"city2name":"克孜勒苏州"},
		{"city2name":"乌恰县"}	]},
	{"city1name":"石河子市","city2":[
		{"city2name":"石河子市"}	]},
	{"city1name":"塔城地区","city2":[
		{"city2name":"额敏县"},
		{"city2name":"和布克赛尔蒙古自治县"},
		{"city2name":"沙湾县"},
		{"city2name":"塔城地区"},
		{"city2name":"塔城市"},
		{"city2name":"托里县"},
		{"city2name":"乌苏市"},
		{"city2name":"裕民县"}	]},
	{"city1name":"图木舒克市","city2":[
		{"city2name":"图木舒克市"}	]},
	{"city1name":"吐鲁番地区","city2":[
		{"city2name":"鄯善县"},
		{"city2name":"吐鲁番地区"},
		{"city2name":"吐鲁番市"},
		{"city2name":"托克逊县"}	]},
	{"city1name":"乌鲁木齐市","city2":[
		{"city2name":"达坂城区"},
		{"city2name":"东山区"},
		{"city2name":"沙依巴克区"},
		{"city2name":"水磨沟区"},
		{"city2name":"天山区"},
		{"city2name":"头屯河区"},
		{"city2name":"乌鲁木齐市"},
		{"city2name":"乌鲁木齐县"},
		{"city2name":"新市区"}	]},
	{"city1name":"五家渠市","city2":[
		{"city2name":"五家渠市"}	]},
	{"city1name":"伊犁州","city2":[
		{"city2name":"察布查尔锡伯自治县"},
		{"city2name":"巩留县"},
		{"city2name":"霍城县"},
		{"city2name":"奎屯市"},
		{"city2name":"尼勒克县"},
		{"city2name":"特克斯县"},
		{"city2name":"新源县"},
		{"city2name":"伊犁州"},
		{"city2name":"伊宁市"},
		{"city2name":"伊宁县"},
		{"city2name":"昭苏县"}	]} ]},
{"provname":"云南","zone":"西南","city1":[
	{"city1name":"保山市","city2":[
		{"city2name":"保山市"},
		{"city2name":"昌宁县"},
		{"city2name":"龙陵县"},
		{"city2name":"隆阳区"},
		{"city2name":"施甸县"},
		{"city2name":"腾冲县"}	]},
	{"city1name":"楚雄州","city2":[
		{"city2name":"楚雄市"},
		{"city2name":"楚雄州"},
		{"city2name":"大姚县"},
		{"city2name":"禄丰县"},
		{"city2name":"牟定县"},
		{"city2name":"南华县"},
		{"city2name":"双柏县"},
		{"city2name":"武定县"},
		{"city2name":"姚安县"},
		{"city2name":"永仁县"},
		{"city2name":"元谋县"}	]},
	{"city1name":"大理州","city2":[
		{"city2name":"宾川县"},
		{"city2name":"大理市"},
		{"city2name":"大理州"},
		{"city2name":"洱源县"},
		{"city2name":"鹤庆县"},
		{"city2name":"剑川县"},
		{"city2name":"弥渡县"},
		{"city2name":"南涧彝族自治县"},
		{"city2name":"巍山彝族回族自治县"},
		{"city2name":"祥云县"},
		{"city2name":"漾濞彝族自治县"},
		{"city2name":"永平县"},
		{"city2name":"云龙县"}	]},
	{"city1name":"德宏州","city2":[
		{"city2name":"德宏州"},
		{"city2name":"梁河县"},
		{"city2name":"陇川县"},
		{"city2name":"潞西市"},
		{"city2name":"瑞丽市"},
		{"city2name":"盈江县"}	]},
	{"city1name":"迪庆州","city2":[
		{"city2name":"德钦县"},
		{"city2name":"迪庆州"},
		{"city2name":"维西傈僳族自治县"},
		{"city2name":"香格里拉县"}	]},
	{"city1name":"红河州","city2":[
		{"city2name":"个旧市"},
		{"city2name":"河口瑶族自治县"},
		{"city2name":"红河县"},
		{"city2name":"红河州"},
		{"city2name":"建水县"},
		{"city2name":"金平苗族瑶族傣族自治县"},
		{"city2name":"开远市"},
		{"city2name":"泸西县"},
		{"city2name":"绿春县"},
		{"city2name":"蒙自县"},
		{"city2name":"弥勒县"},
		{"city2name":"屏边苗族自治县"},
		{"city2name":"石屏县"},
		{"city2name":"元阳县"}	]},
	{"city1name":"昆明市","city2":[
		{"city2name":"安宁市"},
		{"city2name":"呈贡县"},
		{"city2name":"东川区"},
		{"city2name":"富民县"},
		{"city2name":"官渡区"},
		{"city2name":"晋宁县"},
		{"city2name":"昆明市"},
		{"city2name":"禄劝彝族苗族自治县"},
		{"city2name":"盘龙区"},
		{"city2name":"石林彝族自治县"},
		{"city2name":"嵩明县"},
		{"city2name":"五华区"},
		{"city2name":"西山区"},
		{"city2name":"寻甸回族彝族自治县"},
		{"city2name":"宜良县"}	]},
	{"city1name":"丽江市","city2":[
		{"city2name":"古城区"},
		{"city2name":"华坪县"},
		{"city2name":"丽江市"},
		{"city2name":"宁蒗彝族自治县"},
		{"city2name":"永胜县"},
		{"city2name":"玉龙纳西族自治县"}	]},
	{"city1name":"临沧地区","city2":[
		{"city2name":"沧源佤族自治县"},
		{"city2name":"凤庆县"},
		{"city2name":"耿马傣族佤族自治县"},
		{"city2name":"临沧地区"},
		{"city2name":"临沧县"},
		{"city2name":"双江拉祜族佤族布朗族傣族自治县"},
		{"city2name":"永德县"},
		{"city2name":"云县"},
		{"city2name":"镇康县"}	]},
	{"city1name":"怒江州","city2":[
		{"city2name":"福贡县"},
		{"city2name":"贡山独龙族怒族自治县"},
		{"city2name":"兰坪白族普米族自治县"},
		{"city2name":"泸水县"},
		{"city2name":"怒江州"}	]},
	{"city1name":"曲靖市","city2":[
		{"city2name":"富源县"},
		{"city2name":"会泽县"},
		{"city2name":"陆良县"},
		{"city2name":"罗平县"},
		{"city2name":"马龙县"},
		{"city2name":"麒麟区"},
		{"city2name":"曲靖市"},
		{"city2name":"师宗县"},
		{"city2name":"宣威市"},
		{"city2name":"沾益县"}	]},
	{"city1name":"思茅地区","city2":[
		{"city2name":"江城哈尼族彝族自治县"},
		{"city2name":"景东彝族自治县"},
		{"city2name":"景谷傣族彝族自治县"},
		{"city2name":"澜沧拉祜族自治县"},
		{"city2name":"孟连傣族拉祜族佤族自治县"},
		{"city2name":"墨江哈尼族自治县"},
		{"city2name":"普洱哈尼族彝族自治县"},
		{"city2name":"思茅地区"},
		{"city2name":"思茅市"},
		{"city2name":"西盟佤族自治县"},
		{"city2name":"镇沅彝族哈尼族拉祜族自治县"}	]},
	{"city1name":"文山州","city2":[
		{"city2name":"富宁县"},
		{"city2name":"广南县"},
		{"city2name":"麻栗坡县"},
		{"city2name":"马关县"},
		{"city2name":"丘北县"},
		{"city2name":"文山县"},
		{"city2name":"文山州"},
		{"city2name":"西畴县"},
		{"city2name":"砚山县"}	]},
	{"city1name":"西双版纳州","city2":[
		{"city2name":"景洪市"},
		{"city2name":"勐海县"},
		{"city2name":"勐腊县"},
		{"city2name":"西双版纳州"}	]},
	{"city1name":"玉溪市","city2":[
		{"city2name":"澄江县"},
		{"city2name":"峨山彝族自治县"},
		{"city2name":"红塔区"},
		{"city2name":"华宁县"},
		{"city2name":"江川县"},
		{"city2name":"通海县"},
		{"city2name":"新平彝族傣族自治县"},
		{"city2name":"易门县"},
		{"city2name":"玉溪市"},
		{"city2name":"元江哈尼族彝族傣族自治县"}	]},
	{"city1name":"昭通市","city2":[
		{"city2name":"大关县"},
		{"city2name":"鲁甸县"},
		{"city2name":"巧家县"},
		{"city2name":"水富县"},
		{"city2name":"绥江县"},
		{"city2name":"威信县"},
		{"city2name":"盐津县"},
		{"city2name":"彝良县"},
		{"city2name":"永善县"},
		{"city2name":"昭通市"},
		{"city2name":"昭阳区"},
		{"city2name":"镇雄县"}	]} ]},
{"provname":"浙江","zone":"华东","city1":[
	{"city1name":"杭州市","city2":[
		{"city2name":"滨江区"},
		{"city2name":"淳安县"},
		{"city2name":"富阳市"},
		{"city2name":"拱墅区"},
		{"city2name":"杭州市"},
		{"city2name":"建德市"},
		{"city2name":"江干区"},
		{"city2name":"临安市"},
		{"city2name":"上城区"},
		{"city2name":"桐庐县"},
		{"city2name":"西湖区"},
		{"city2name":"下城区"},
		{"city2name":"萧山区"},
		{"city2name":"余杭区"}	]},
	{"city1name":"湖州市","city2":[
		{"city2name":"安吉县"},
		{"city2name":"长兴县"},
		{"city2name":"德清县"},
		{"city2name":"湖州市"},
		{"city2name":"南浔"}	]},
	{"city1name":"嘉兴","city2":[
		{"city2name":"海宁市"},
		{"city2name":"海盐县"},
		{"city2name":"嘉善县"},
		{"city2name":"嘉兴"},
		{"city2name":"平湖市"},
		{"city2name":"桐乡市"},
		{"city2name":"秀城区"},
		{"city2name":"秀洲区"},
		{"city2name":"乍浦"}	]},
	{"city1name":"金华市","city2":[
		{"city2name":"东阳市"},
		{"city2name":"金东区"},
		{"city2name":"金华市"},
		{"city2name":"兰溪市"},
		{"city2name":"磐安县"},
		{"city2name":"浦江县"},
		{"city2name":"武义县"},
		{"city2name":"婺城区"},
		{"city2name":"义乌市"},
		{"city2name":"永康市"}	]},
	{"city1name":"丽水市","city2":[
		{"city2name":"缙云县"},
		{"city2name":"景宁畲族自治县"},
		{"city2name":"丽水市"},
		{"city2name":"莲都区"},
		{"city2name":"龙泉市"},
		{"city2name":"青田县"},
		{"city2name":"庆元县"},
		{"city2name":"松阳县"},
		{"city2name":"遂昌县"},
		{"city2name":"云和县"}	]},
	{"city1name":"宁波市","city2":[
		{"city2name":"北仑区"},
		{"city2name":"慈溪市"},
		{"city2name":"奉化市"},
		{"city2name":"海曙区"},
		{"city2name":"江北区"},
		{"city2name":"江东区"},
		{"city2name":"宁波市"},
		{"city2name":"宁海县"},
		{"city2name":"象山县"},
		{"city2name":"鄞州区"},
		{"city2name":"余姚市"},
		{"city2name":"镇海区"}	]},
	{"city1name":"衢州市","city2":[
		{"city2name":"常山县"},
		{"city2name":"江山市"},
		{"city2name":"开化县"},
		{"city2name":"柯城区"},
		{"city2name":"龙游县"},
		{"city2name":"衢江区"},
		{"city2name":"衢州市"}	]},
	{"city1name":"绍兴市","city2":[
		{"city2name":"柯桥镇"},
		{"city2name":"上虞市"},
		{"city2name":"绍兴市"},
		{"city2name":"绍兴县"},
		{"city2name":"嵊州市"},
		{"city2name":"新昌县"},
		{"city2name":"越城区"},
		{"city2name":"诸暨市"}	]},
	{"city1name":"台州市","city2":[
		{"city2name":"黄岩区"},
		{"city2name":"椒江区"},
		{"city2name":"临海市"},
		{"city2name":"路桥区"},
		{"city2name":"三门县"},
		{"city2name":"台州市"},
		{"city2name":"天台县"},
		{"city2name":"温岭市"},
		{"city2name":"仙居县"},
		{"city2name":"玉环县"}	]},
	{"city1name":"温州","city2":[
		{"city2name":"苍南县"},
		{"city2name":"洞头县"},
		{"city2name":"乐清市"},
		{"city2name":"龙港"},
		{"city2name":"龙湾区"},
		{"city2name":"鹿城区"},
		{"city2name":"瓯海区"},
		{"city2name":"平阳县"},
		{"city2name":"瑞安市"},
		{"city2name":"泰顺县"},
		{"city2name":"温州"},
		{"city2name":"文成县"},
		{"city2name":"永嘉县"}	]},
	{"city1name":"舟山市","city2":[
		{"city2name":"岱山县"},
		{"city2name":"定海区"},
		{"city2name":"普陀区"},
		{"city2name":"嵊泗县"},
		{"city2name":"舟山市"}	]} ]},
{"provname":"重庆","zone":"西南","city1":[
	{"city1name":"重庆","city2":[
		{"city2name":"巴南区"},
		{"city2name":"北碚区"},
		{"city2name":"璧山县"},
		{"city2name":"长寿区"},
		{"city2name":"城口县"},
		{"city2name":"大渡口区"},
		{"city2name":"大足县"},
		{"city2name":"垫江县"},
		{"city2name":"丰都县"},
		{"city2name":"奉节县"},
		{"city2name":"涪陵区"},
		{"city2name":"合川市"},
		{"city2name":"江北区"},
		{"city2name":"江津市"},
		{"city2name":"九龙坡区"},
		{"city2name":"开县"},
		{"city2name":"梁平县"},
		{"city2name":"南岸区"},
		{"city2name":"南川市"},
		{"city2name":"彭水苗族土家族自治县"},
		{"city2name":"綦江县"},
		{"city2name":"黔江区"},
		{"city2name":"荣昌县"},
		{"city2name":"沙坪坝区"},
		{"city2name":"石柱土家族自治县"},
		{"city2name":"双桥区"},
		{"city2name":"铜梁县"},
		{"city2name":"潼南县"},
		{"city2name":"万盛区"},
		{"city2name":"万州区"},
		{"city2name":"巫山县"},
		{"city2name":"巫溪县"},
		{"city2name":"武隆县"},
		{"city2name":"秀山土家族苗族自治县"},
		{"city2name":"永川市"},
		{"city2name":"酉阳土家族苗族自治县"},
		{"city2name":"渝北区"},
		{"city2name":"渝中区"},
		{"city2name":"云阳县"},
		{"city2name":"忠县"},
		{"city2name":"重庆"}	]}	]},
{"provname":"台湾","zone":"华南","city1":[
	{"city1name":"台湾","city2":[
		{"city2name":"台湾"}	]}	]}
]

